'\" t
.nh
.TH podman-network-ls 1
.SH NAME
podman-network-ls \- Display a summary of networks

.SH SYNOPSIS
\fBpodman network ls\fP  [\fIoptions\fP]

.SH DESCRIPTION
Displays a list of existing podman networks.

.SH OPTIONS
.SS \fB--filter\fP, \fB-f\fP=\fIfilter=value\fP
Provide filter values.

.PP
The \fIfilters\fP argument format is of \fBkey=value\fR\&. If there is more than one \fIfilter\fP, then pass multiple OPTIONS: \fB--filter\fP \fIfoo=bar\fP \fB--filter\fP \fIbif=baz\fP\&.

.PP
Supported filters:

.TS
allbox;
l l 
l l .
\fB\fBFilter\fP\fP	\fB\fBDescription\fP\fP
driver	Filter by driver type.
id	T{
Filter by full or partial network ID.
T}
label	T{
Filter by network with (or without, in the case of label!=[...] is used) the specified labels.
T}
name	T{
Filter by network name (accepts \fBregex\fR).
T}
until	T{
Filter by networks created before given timestamp.
T}
dangling	T{
Filter by networks with no containers attached.
T}
.TE

.PP
The \fBdriver\fR filter accepts values: \fBbridge\fR, \fBmacvlan\fR, \fBipvlan\fR\&.

.PP
The \fBlabel\fR \fIfilter\fP accepts two formats. One is the \fBlabel\fR=\fIkey\fP or \fBlabel\fR=\fIkey\fP=\fIvalue\fP, which shows networks with the specified labels. The other format is the \fBlabel!\fR=\fIkey\fP or \fBlabel!\fR=\fIkey\fP=\fIvalue\fP, which shows networks without the specified labels.

.PP
The \fBuntil\fR \fIfilter\fP can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. 10m, 1h30m) computed relative to the machine's time.

.PP
The \fBdangling\fR \fIfilter\fP accepts values \fBtrue\fR or \fBfalse\fR\&.

.SS \fB--format\fP=\fIformat\fP
Change the default output format.  This can be of a supported type like 'json'
or a Go template.
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Created ...	T{
Timestamp when the network was created
T}
\&.DNSEnabled	T{
Network has dns enabled (boolean)
T}
\&.Driver	Network driver
\&.ID	Network ID
\&.Internal	Network is internal (boolean)
\&.IPAMOptions ...	Network ipam options
\&.IPv6Enabled	T{
Network has ipv6 subnet (boolean)
T}
\&.Labels	Network labels
\&.Name	Network name
\&.NetworkDNSServers	T{
Array of DNS servers used in this network
T}
\&.NetworkInterface	T{
Name of the network interface on the host
T}
\&.Options ...	Network options
\&.Routes	T{
List of static routes for this network
T}
\&.Subnets	T{
List of subnets on this network
T}
.TE

.SS \fB--no-trunc\fP
Do not truncate the network ID.

.SS \fB--noheading\fP, \fB-n\fP
Omit the table headings from the listing.

.SS \fB--quiet\fP, \fB-q\fP
The \fBquiet\fR option restricts the output to only the network names.

.SH EXAMPLE
Display networks:

.EX
$ podman network ls
NETWORK ID    NAME         DRIVER
88a7120ee19d  podman       bridge
6dd508dbf8cd  podman6  bridge
8e35c2cd3bf6  podman5  macvlan
.EE

.PP
Display only network names:

.EX
$ podman network ls -q
podman
podman2
outside
podman9
.EE

.PP
Display name of network which support bridge plugin:

.EX
$ podman network ls --filter driver=bridge --format {{.Name}}
podman
podman2
podman9
.EE

.PP
List networks with their subnets:

.EX
$ podman network ls --format "{{.Name}}: {{range .Subnets}}{{.Subnet}} {{end}}"
podman: 10.88.0.0/16
podman3: 10.89.30.0/24 fde4:f86f:4aab:e68f::/64
macvlan:
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP, \fBpodman-network-inspect(1)\fP, \fBpodman-network-create(1)\fP

.SH HISTORY
August 2021, Updated with the new network format by Paul Holzinger pholzing@redhat.com
\[la]mailto:pholzing@redhat.com\[ra]

.PP
August 2019, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
