.nh
.TH podman-export 1
.SH NAME
podman-export \- Export a container's filesystem contents as a tar archive

.SH SYNOPSIS
\fBpodman export\fP [\fIoptions\fP] \fIcontainer\fP

.PP
\fBpodman container export\fP [\fIoptions\fP] \fIcontainer\fP

.SH DESCRIPTION
\fBpodman export\fP exports the filesystem of a container and saves it as a tarball
on the local machine. \fBpodman export\fP writes to STDOUT by default and can be
redirected to a file using the \fB--output\fR flag.
The image of the container exported by \fBpodman export\fP can be imported by \fBpodman import\fP\&.
To export image(s) with parent layers, use \fBpodman save\fP\&.
Note: \fB:\fR is a restricted character and cannot be part of the file name.

.PP
\fBpodman [GLOBAL OPTIONS]\fP

.PP
\fBpodman export [GLOBAL OPTIONS]\fP

.PP
\fBpodman export [OPTIONS] CONTAINER\fP

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--output\fP, \fB-o\fP
Write to a file, default is STDOUT

.SH EXAMPLES
Export container into specified tar ball:

.EX
$ podman export -o redis-container.tar 883504668ec465463bc0fe7e63d53154ac3b696ea8d7b233748918664ea90e57
.EE

.PP
Export container to stdout:

.EX
$ podman export 883504668ec465463bc0fe7e63d53154ac3b696ea8d7b233748918664ea90e57 > redis-container.tar
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-import(1)\fP

.SH HISTORY
August 2017, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
