.nh
.TH podman-manifest-push 1
.SH NAME
podman-manifest-push \- Push a manifest list or image index to a registry

.SH SYNOPSIS
\fBpodman manifest push\fP [\fIoptions\fP] \fIlistnameorindexname\fP [\fIdestination\fP]

.SH DESCRIPTION
Pushes a manifest list or image index to a registry.

.SH RETURN VALUE
The list image's ID and the digest of the image's manifest.

.SH OPTIONS
.SS \fB--add-compression\fP=\fIcompression\fP
Makes sure that requested compression variant for each platform is added to the manifest list keeping original instance
intact in the same manifest list. Supported values are (\fBgzip\fR, \fBzstd\fR and \fBzstd:chunked\fR). Following flag can be used
multiple times.

.PP
Note that \fB--compression-format\fR controls the compression format of each instance in the manifest list. \fB--add-compression\fR
will add another variant for each instance in the list with the specified compressions. \fB--compression-format\fR gzip \fB--add-compression\fR
zstd will push a manifest list with each instance being compressed with gzip plus an additional variant of each instance
being compressed with zstd.

.SS \fB--all\fP
Push the images mentioned in the manifest list or image index, in addition to
the list or index itself. (Default true)

.SS \fB--authfile\fP=\fIpath\fP
Path of the authentication file. Default is \fB${XDG_RUNTIME_DIR}/containers/auth.json\fR on Linux, and \fB$HOME/.config/containers/auth.json\fR on Windows/macOS.
The file is created by \fBpodman login\fP\&. If the authorization state is not found there, \fB$HOME/.docker/config.json\fR is checked, which is set using \fBdocker login\fP\&.

.PP
Note: There is also the option to override the default path of the authentication file by setting the \fBREGISTRY_AUTH_FILE\fR environment variable. This can be done with \fBexport REGISTRY_AUTH_FILE=\fIpath\fP\fP\&.

.SS \fB--cert-dir\fP=\fIpath\fP
Use certificates at \fIpath\fP (*\&.crt, *\&.cert, *\&.key) to connect to the registry. (Default: /etc/containers/certs.d)
For details, see \fBcontainers-certs.d(5)\fP\&.
(This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--compression-format\fP=\fBgzip\fP | \fIzstd\fP | \fIzstd:chunked\fP
Specifies the compression format to use.  Supported values are: \fBgzip\fR, \fBzstd\fR and \fBzstd:chunked\fR\&.  The default is \fBgzip\fR unless overridden in the containers.conf file.
\fBzstd:chunked\fR is incompatible with encrypting images, and will be treated as \fBzstd\fR with a warning in that case.

.SS \fB--compression-level\fP=\fIlevel\fP
Specifies the compression level to use.  The value is specific to the compression algorithm used, e.g. for zstd the accepted values are in the range 1-20 (inclusive) with a default of 3, while for gzip it is 1-9 (inclusive) and has a default of 5.

.SS \fB--creds\fP=\fI[username[:password]]\fP
The [username[:password]] to use to authenticate with the registry, if required.
If one or both values are not supplied, a command line prompt appears and the
value can be entered. The password is entered without echo.

.PP
Note that the specified credentials are only used to authenticate against
target registries.  They are not used for mirrors or when the registry gets
rewritten (see \fBcontainers-registries.conf(5)\fR); to authenticate against those
consider using a \fBcontainers-auth.json(5)\fR file.

.SS \fB--digestfile\fP=\fIDigestfile\fP
After copying the image, write the digest of the resulting image to the file.

.SS \fB--force-compression\fP
If set, push uses the specified compression algorithm even if the destination contains a differently-compressed variant already.
Defaults to \fBtrue\fR if \fB--compression-format\fR is explicitly specified on the command-line, \fBfalse\fR otherwise.

.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Manifest list type (oci or v2s2) to use when pushing the list (default is oci).

.SS \fB--quiet\fP, \fB-q\fP
When writing the manifest, suppress progress output

.SS \fB--remove-signatures\fP
Don't copy signatures when pushing images.

.SS \fB--rm\fP
Delete the manifest list or image index from local storage if pushing succeeds.

.SS \fB--sign-by\fP=\fIfingerprint\fP
Sign the pushed images with a “simple signing” signature using the specified key. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-by-sigstore\fP=\fIparam-file\fP
Add a sigstore signature based on further options specified in a container's sigstore signing parameter file \fIparam-file\fP\&.
See containers-sigstore-signing-params.yaml(5) for details about the file format.

.SS \fB--sign-by-sigstore-private-key\fP=\fIpath\fP
Sign the pushed images with a sigstore signature using a private key at the specified path. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-by-sq-fingerprint\fP=\fIfingerprint\fP
Add a “simple signing” signature using a Sequoia-PGP key with the specified fingerprint.
(This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-passphrase-file\fP=\fIpath\fP
If signing the image (using \fB--sign-by\fP, \fBsign-by-sq-fingerprint\fP or \fB--sign-by-sigstore-private-key\fP), read the passphrase to use from the specified path.

.SS \fB--tls-verify\fP
Require HTTPS and verify certificates when contacting registries (default: \fBtrue\fP).
If explicitly set to \fBtrue\fP, TLS verification is used.
If set to \fBfalse\fP, TLS verification is not used.
If not specified, TLS verification is used unless the target registry
is listed as an insecure registry in \fBcontainers-registries.conf(5)\fP

.SH DESTINATION
DESTINATION is the location the container image is pushed to. It supports all transports from \fBcontainers-transports(5)\fR\&. If no transport is specified, the \fBdocker\fR (i.e., container registry) transport is used.  For remote clients, including Mac and Windows (excluding WSL2) machines, \fBdocker\fR is the only supported transport.

.SH EXAMPLES
Push manifest list to container registry:

.EX
podman manifest push mylist:v1.11 docker://registry.example.org/mylist:v1.11
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-manifest(1)\fP, \fBcontainers-transports(5)\fP
