.nh
.TH podman-pod-start 1
.SH NAME
podman-pod-start \- Start one or more pods

.SH SYNOPSIS
\fBpodman pod start\fP [\fIoptions\fP] \fIpod\fP ...

.SH DESCRIPTION
Start containers in one or more pods.  You may use pod IDs or names as input. The pod must have a container attached
to be started.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Starts all pods

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, use the last created pod.
Note: the last started pod can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--pod-id-file\fP=\fIfile\fP
Read pod ID from the specified \fIfile\fP and start the pod. Can be specified multiple times.

.SH EXAMPLE
Start pod with a given name:

.EX
podman pod start mywebserverpod
.EE

.PP
Start pods with given IDs:

.EX
podman pod start 860a4b23 5421ab4
.EE

.PP
Start the latest pod. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines):

.EX
podman pod start --latest
.EE

.PP
Start all pods:

.EX
podman pod start --all
.EE

.PP
Start pod using ID specified in a given file:

.EX
podman pod start --pod-id-file /path/to/id/file
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-pod-stop(1)\fP

.SH HISTORY
July 2018, Adapted from podman start man page by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
