.nh
.TH podman-volume-rm 1
.SH NAME
podman-volume-rm \- Remove one or more volumes

.SH SYNOPSIS
\fBpodman volume rm\fP [\fIoptions\fP] \fIvolume\fP [...]

.SH DESCRIPTION
Removes one or more volumes. Only volumes that are not being used are removed.
If a volume is being used by a container, an error is returned unless the \fB--force\fP
flag is being used. To remove all volumes, use the \fB--all\fP flag.
Volumes can be removed individually by providing their full name or a unique partial name.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all volumes.

.SS \fB--force\fP, \fB-f\fP
Remove a volume by force.
If it is being used by containers, the containers are removed first.

.SS \fB--help\fP
Print usage statement

.SS \fB--time\fP, \fB-t\fP=\fIseconds\fP
Seconds to wait before forcibly stopping running containers that are using the specified volume. The --force option must be specified to use the --time option. Use -1 for infinite wait.

.SH EXAMPLES
Remove multiple specified volumes.

.EX
$ podman volume rm myvol1 myvol2
.EE

.PP
Remove all volumes.

.EX
$ podman volume rm --all
.EE

.PP
Remove the specified volume even if it is in use. Note, this removes all containers using the volume.

.EX
$ podman volume rm --force myvol
.EE

.SH Exit Status
\fB0\fP   All specified volumes removed

.PP
\fB1\fP   One of the specified volumes did not exist, and no other failures

.PP
\fB2\fP   One of the specified volumes is being used by a container

.PP
\fB125\fP The command fails for any other reason

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP

.SH HISTORY
November 2018, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
