'\" t
.nh
.TH podman-history 1
.SH NAME
podman-history \- Show the history of an image

.SH SYNOPSIS
\fBpodman history\fP [\fIoptions\fP] \fIimage\fP[:\fItag\fP|@\fIdigest\fP]

.PP
\fBpodman image history\fP [\fIoptions\fP] \fIimage\fP[:\fItag\fP|@\fIdigest\fP]

.SH DESCRIPTION
\fBpodman history\fP displays the history of an image by printing out information
about each layer used in the image. The information printed out for each layer
include Created (time and date), Created By, Size, and Comment. The output can
be truncated or not using the \fB--no-trunc\fP flag. If the \fB--human\fP flag is
set, the time of creation and size are printed out in a human readable format.
The \fB--quiet\fP flag displays the ID of the image only when set and the \fB--format\fP
flag is used to print the information using the Go template provided by the user.

.SH OPTIONS
.SS \fB--format\fP=\fIformat\fP
Alter the output for a format like 'json' or a Go template.

.PP
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Comment	Comment for the layer
\&.Created	T{
if --human, time elapsed since creation, otherwise time stamp of creation
T}
\&.CreatedAt	T{
Time when the image layer was created
T}
\&.CreatedBy	T{
Command used to create the layer
T}
\&.CreatedSince	T{
Elapsed time since the image layer was created
T}
\&.ID	Image ID
\&.Size	Size of layer on disk
\&.Tags	Image tags
.TE

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--human\fP, \fB-H\fP
Display sizes and dates in human readable format (default \fItrue\fP).

.SS \fB--no-trunc\fP
Do not truncate the output (default \fIfalse\fP).

.SS \fB--quiet\fP, \fB-q\fP
Print the numeric IDs only (default \fIfalse\fP).

.SH EXAMPLES
Show the history of the specified image:

.EX
$ podman history debian
ID              CREATED       CREATED BY                                      SIZE       COMMENT
b676ca55e4f2c   9 weeks ago   /bin/sh -c #(nop) CMD ["bash"]                  0 B
<missing>       9 weeks ago   /bin/sh -c #(nop) ADD file:ebba725fb97cea4...   45.14 MB
.EE

.PP
Show the history of the specified image without truncating content and using raw data:

.EX
$ podman history --no-trunc=true --human=false debian
ID              CREATED                CREATED BY                                      SIZE       COMMENT
b676ca55e4f2c   2017-07-24T16:52:55Z   /bin/sh -c #(nop) CMD ["bash"]                  0
<missing>       2017-07-24T16:52:54Z   /bin/sh -c #(nop) ADD file:ebba725fb97cea4...   45142935
.EE

.PP
Show the formatted history of the specified image:

.EX
$ podman history --format "{{.ID}} {{.Created}}" debian
b676ca55e4f2c   9 weeks ago
<missing>       9 weeks ago
.EE

.PP
Show the history in JSON format for the specified image:

.EX
$ podman history --format json debian
[
    {
	"id": "b676ca55e4f2c0ce53d0636438c5372d3efeb5ae99b676fa5a5d1581bad46060",
	"created": "2017-07-24T16:52:55.195062314Z",
	"createdBy": "/bin/sh -c #(nop)  CMD [\\"bash\\"]",
	"size": 0,
	"comment": ""
    },
    {
	"id": "b676ca55e4f2c0ce53d0636438c5372d3efeb5ae99b676fa5a5d1581bad46060",
	"created": "2017-07-24T16:52:54.898893387Z",
	"createdBy": "/bin/sh -c #(nop) ADD file:ebba725fb97cea45d0b1b35ccc8144e766fcfc9a78530465c23b0c4674b14042 in / ",
	"size": 45142935,
	"comment": ""
    }
]
.EE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
July 2017, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
