.nh
.TH podman-push 1
.SH NAME
podman-push \- Push an image, manifest list or image index from local storage to elsewhere

.SH SYNOPSIS
\fBpodman push\fP [\fIoptions\fP] \fIimage\fP [\fIdestination\fP]

.PP
\fBpodman image push\fP [\fIoptions\fP] \fIimage\fP [\fIdestination\fP]

.SH DESCRIPTION
Pushes an image, manifest list or image index from local storage to a specified
destination.

.SH Image storage
Images are pushed from those stored in local image storage.

.SH DESTINATION
DESTINATION is the location the container image is pushed to. It supports all transports from \fBcontainers-transports(5)\fR\&. If no transport is specified, the \fBdocker\fR (i.e., container registry) transport is used.  For remote clients, including Mac and Windows (excluding WSL2) machines, \fBdocker\fR is the only supported transport.

.EX
# Push to a container registry
$ podman push quay.io/podman/stable

# Push to a container registry via the docker transport
$ podman push docker://quay.io/podman/stable

# Push to a container registry with another tag
$ podman push myimage quay.io/username/myimage

# Push to a local directory
$ podman push myimage dir:/tmp/myimage

# Push to a tarball in the docker-archive format
$ podman push myimage docker-archive:/tmp/myimage

# Push to a local docker daemon
$ sudo podman push myimage docker-daemon:docker.io/library/myimage:33

# Push to a tarball in the OCI format
$ podman push myimage oci-archive:/tmp/myimage
.EE

.SH OPTIONS
.SS \fB--authfile\fP=\fIpath\fP
Path of the authentication file. Default is \fB${XDG_RUNTIME_DIR}/containers/auth.json\fR on Linux, and \fB$HOME/.config/containers/auth.json\fR on Windows/macOS.
The file is created by \fBpodman login\fP\&. If the authorization state is not found there, \fB$HOME/.docker/config.json\fR is checked, which is set using \fBdocker login\fP\&.

.PP
Note: There is also the option to override the default path of the authentication file by setting the \fBREGISTRY_AUTH_FILE\fR environment variable. This can be done with \fBexport REGISTRY_AUTH_FILE=\fIpath\fP\fP\&.

.SS \fB--cert-dir\fP=\fIpath\fP
Use certificates at \fIpath\fP (*\&.crt, *\&.cert, *\&.key) to connect to the registry. (Default: /etc/containers/certs.d)
For details, see \fBcontainers-certs.d(5)\fP\&.
(This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--compress\fP
Compress tarball image layers when pushing to a directory using the 'dir' transport. (default is same compression type, compressed or uncompressed, as source)

.PP
Note: This flag can only be set when using the \fBdir\fP transport

.SS \fB--compression-format\fP=\fBgzip\fP | \fIzstd\fP | \fIzstd:chunked\fP
Specifies the compression format to use.  Supported values are: \fBgzip\fR, \fBzstd\fR and \fBzstd:chunked\fR\&.  The default is \fBgzip\fR unless overridden in the containers.conf file.
\fBzstd:chunked\fR is incompatible with encrypting images, and will be treated as \fBzstd\fR with a warning in that case.

.SS \fB--compression-level\fP=\fIlevel\fP
Specifies the compression level to use.  The value is specific to the compression algorithm used, e.g. for zstd the accepted values are in the range 1-20 (inclusive) with a default of 3, while for gzip it is 1-9 (inclusive) and has a default of 5.

.SS \fB--creds\fP=\fI[username[:password]]\fP
The [username[:password]] to use to authenticate with the registry, if required.
If one or both values are not supplied, a command line prompt appears and the
value can be entered. The password is entered without echo.

.PP
Note that the specified credentials are only used to authenticate against
target registries.  They are not used for mirrors or when the registry gets
rewritten (see \fBcontainers-registries.conf(5)\fR); to authenticate against those
consider using a \fBcontainers-auth.json(5)\fR file.

.SS \fB--digestfile\fP=\fIDigestfile\fP
After copying the image, write the digest of the resulting image to the file.

.SS \fB--disable-content-trust\fP
This is a Docker-specific option to disable image verification to a container
registry and is not supported by Podman. This option is a NOOP and provided
solely for scripting compatibility.

.SS \fB--encrypt-layer\fP=\fIlayer(s)\fP
Layer(s) to encrypt: 0-indexed layer indices with support for negative indexing (e.g. 0 is the first layer, -1 is the last layer). If not defined, encrypts all layers if encryption-key flag is specified.

.SS \fB--encryption-key\fP=\fIkey\fP
The [protocol:keyfile] specifies the encryption protocol, which can be JWE (RFC7516), PGP (RFC4880), and PKCS7 (RFC2315) and the key material required for image encryption. For instance, jwe:/path/to/key.pem or pgp:admin@example.com or pkcs7:/path/to/x509-file.

.SS \fB--force-compression\fP
If set, push uses the specified compression algorithm even if the destination contains a differently-compressed variant already.
Defaults to \fBtrue\fR if \fB--compression-format\fR is explicitly specified on the command-line, \fBfalse\fR otherwise.

.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Manifest Type (oci, v2s2, or v2s1) to use when pushing an image.

.SS \fB--quiet\fP, \fB-q\fP
When writing the output image, suppress progress output

.SS \fB--remove-signatures\fP
Discard any pre-existing signatures in the image.

.SS \fB--retry\fP=\fIattempts\fP
Number of times to retry pulling or pushing images between the registry and
local storage in case of failure. Default is \fB3\fP\&.

.SS \fB--retry-delay\fP=\fIduration\fP
Duration of delay between retry attempts when pulling or pushing images between
the registry and local storage in case of failure. The default is to start at two seconds and then exponentially back off. The delay is used when this value is set, and no exponential back off occurs.

.SS \fB--sign-by\fP=\fIkey\fP
Add a “simple signing” signature at the destination using the specified key. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-by-sigstore\fP=\fIparam-file\fP
Add a sigstore signature based on further options specified in a container's sigstore signing parameter file \fIparam-file\fP\&.
See containers-sigstore-signing-params.yaml(5) for details about the file format.

.SS \fB--sign-by-sigstore-private-key\fP=\fIpath\fP
Add a sigstore signature at the destination using a private key at the specified path. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-by-sq-fingerprint\fP=\fIfingerprint\fP
Add a “simple signing” signature using a Sequoia-PGP key with the specified fingerprint.
(This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SS \fB--sign-passphrase-file\fP=\fIpath\fP
If signing the image (using \fB--sign-by\fP, \fBsign-by-sq-fingerprint\fP or \fB--sign-by-sigstore-private-key\fP), read the passphrase to use from the specified path.

.SS \fB--tls-verify\fP
Require HTTPS and verify certificates when contacting registries (default: \fBtrue\fP).
If explicitly set to \fBtrue\fP, TLS verification is used.
If set to \fBfalse\fP, TLS verification is not used.
If not specified, TLS verification is used unless the target registry
is listed as an insecure registry in \fBcontainers-registries.conf(5)\fP

.SH EXAMPLES
Push the specified image to a local directory:

.EX
# podman push imageID dir:/path/to/image
.EE

.PP
Push the specified image to a local directory in OCI format:

.EX
# podman push imageID oci-archive:/path/to/layout:image:tag
.EE

.PP
Push the specified image to a container registry:

.EX
# podman push imageID docker://registry.example.com/repository:tag
.EE

.PP
Push the specified image to a container registry and save the digest in the specified file:

.EX
# podman push --digestfile=/tmp/mydigest imageID docker://registry.example.com/repository:tag
.EE

.PP
Push the specified image into the local Docker daemon container store:

.EX
# podman push imageID docker-daemon:image:tag
.EE

.PP
Push the specified image with a different image name using credentials from an alternate authfile path:

.EX
# podman push --authfile temp-auths/myauths.json alpine docker://docker.io/umohnani/alpine
Getting image source signatures
Copying blob sha256:5bef08742407efd622d243692b79ba0055383bbce12900324f75e56f589aedb0
 4.03 MB / 4.03 MB [========================================================] 1s
Copying config sha256:ad4686094d8f0186ec8249fc4917b71faa2c1030d7b5a025c29f26e19d95c156
 1.41 KB / 1.41 KB [========================================================] 1s
Writing manifest to image destination
Storing signatures
.EE

.PP
Push the specified image to a local directory as an OCI image:

.EX
# podman push --format oci registry.access.redhat.com/rhel7 dir:rhel7-dir
Getting image source signatures
Copying blob sha256:9cadd93b16ff2a0c51ac967ea2abfadfac50cfa3af8b5bf983d89b8f8647f3e4
 71.41 MB / 71.41 MB [======================================================] 9s
Copying blob sha256:4aa565ad8b7a87248163ce7dba1dd3894821aac97e846b932ff6b8ef9a8a508a
 1.21 KB / 1.21 KB [========================================================] 0s
Copying config sha256:f1b09a81455c351eaa484b61aacd048ab613c08e4c5d1da80c4c46301b03cf3b
 3.01 KB / 3.01 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pull(1)\fP, \fBpodman-login(1)\fP, \fBcontainers-certs.d(5)\fP, \fBcontainers-registries.conf(5)\fP, \fBcontainers-transports(5)\fP

.SS Troubleshooting
See podman-troubleshooting(7)
for solutions to common issues.
