.nh
.TH podman-image-exists 1
.SH NAME
podman-image-exists \- Check if an image exists in local storage

.SH SYNOPSIS
\fBpodman image exists\fP \fIimage\fP

.SH DESCRIPTION
\fBpodman image exists\fP checks if an image exists in local storage. The \fBID\fP or \fBName\fP
of the image may be used as input.  Podman returns an exit code
of \fB0\fR when the image is found.  A \fB1\fR is returned otherwise. An exit code of \fB125\fR indicates there
was an issue accessing the local storage.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLES
Check if an image called \fBwebclient\fR exists in local storage (the image does actually exist):

.EX
$ podman image exists webclient
$ echo $?
0
.EE

.PP
Check if an image called \fBwebbackend\fR exists in local storage (the image does not actually exist):

.EX
$ podman image exists webbackend
$ echo $?
1
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-image(1)\fP

.SH HISTORY
November 2018, Originally compiled by Brent Baude (bbaude at redhat dot com)
