'\" t
.nh
.TH podman-diff 1
.SH NAME
podman-diff \- Inspect changes on a container or image's filesystem

.SH SYNOPSIS
\fBpodman diff\fP [\fIoptions\fP] \fIcontainer|image\fP [\fIcontainer|image\fP]

.SH DESCRIPTION
Displays changes on a container or image's filesystem.  The container or image is compared to its parent layer or the second argument when given.

.PP
The output is prefixed with the following symbols:

.TS
allbox;
l l 
l l .
\fBSymbol\fP	\fBDescription\fP
A	A file or directory was added.
D	T{
A file or directory was deleted.
T}
C	T{
A file or directory was changed.
T}
.TE

.SH OPTIONS
.SS \fB--format\fP
Alter the output into a different format.  The only valid format for \fBpodman diff\fP is \fBjson\fR\&.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SH EXAMPLES
Show container-modified files versus the container's image:

.EX
$ podman diff container1
A /myscript.sh
.EE

.PP
Show container-modified files versus the container's image in JSON format:

.EX
$ podman diff --format json myimage
{
  "changed": [
    "/usr",
    "/usr/local",
    "/usr/local/bin"
  ],
  "added": [
    "/usr/local/bin/docker-entrypoint.sh"
  ]
}
.EE

.PP
Show the difference between the specified container and the image:

.EX
$ podman diff container1 image1
A /test
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-container-diff(1)\fP, \fBpodman-image-diff(1)\fP

.SH HISTORY
August 2017, Originally compiled by Ryan Cole rycole@redhat.com
\[la]mailto:rycole@redhat.com\[ra]
