.nh
.TH podman-healthcheck-run 1
.SH NAME
podman-healthcheck-run \- Run a container healthcheck

.SH SYNOPSIS
\fBpodman healthcheck run\fP \fIcontainer\fP

.SH DESCRIPTION
Runs the healthcheck command defined in a running container manually.  The resulting error codes are defined
as follows:
.IP \(bu 2
0 = healthcheck command succeeded
.IP \(bu 2
1 = healthcheck command failed
.IP \(bu 2
125 = an error has occurred

.PP
Possible errors that can occur during the healthcheck are:
* unable to find the container
* container has no defined healthcheck
* container is not running

.SH OPTIONS
.SS \fB--help\fP
Print usage statement

.SH EXAMPLES
Run healthchecks in specified container:

.EX
$ podman healthcheck run mywebapp
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-healthcheck(1)\fP

.SH HISTORY
Feb 2019, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
