'\" t
.nh
.TH podman-system-connection-list 1
.SH NAME
podman-system-connection-list \- List the destination for the Podman service(s)

.SH SYNOPSIS
\fBpodman system connection list\fP [\fIoptions\fP]

.PP
\fBpodman system connection ls\fP [\fIoptions\fP]

.SH DESCRIPTION
List ssh destination(s) for podman service(s).

.SH OPTIONS
.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Change the default output format.  This can be of a supported type like 'json' or a Go template.
Valid placeholders for the Go template listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Default	T{
Indicates whether connection is the default
T}
\&.Identity	T{
Path to file containing SSH identity
T}
\&.Name	Connection Name/Identifier
\&.ReadWrite	T{
Indicates if this connection can be modified using the system connection commands
T}
\&.TLSCA	T{
Path to a PEM file containing the certificate authority bundle to verify the server's certificate against.
T}
\&.TLSCert	T{
Path to a PEM file containing the certificate authority bundle to verify the server's certificate against.
T}
\&.TLSKey	T{
Path to a PEM file containing the private key matching \fB\&.TLSCA\fR
T}
\&.URI	T{
URI to podman service. Valid schemes are ssh://[user@]\fIhost\fP[:port]\fIUnix domain socket\fP[?secure=True], unix://\fIUnix domain socket\fP, and tcp://localhost[:\fIport\fP]
T}
.TE

.SS \fB--quiet\fP, \fB-q\fP
Only show connection names

.SH EXAMPLE
List system connections:

.EX
$ podman system connection list
Name URI                                                      Identity	    Default  ReadWrite
deva ssh://root@example.com:/run/podman/podman.sock           ~/.ssh/id_rsa true     true
devb ssh://user@example.com:/run/user/1000/podman/podman.sock ~/.ssh/id_rsa false    true
.EE

.PP
Show connections in JSON format:

.EX
$ podman system connection list --format json
[
    {
        "Name": "podman-machine-default",
        "URI": "ssh://core@127.0.0.1:53298/run/user/501/podman/podman.sock",
        "Identity": "/Users/ragm/.local/share/containers/podman/machine/machine",
        "IsMachine": true,
        "Default": true,
        "ReadWrite": true
    },
    {
        "Name": "podman-machine-default-root",
        "URI": "ssh://root@127.0.0.1:53298/run/podman/podman.sock",
        "Identity": "/Users/ragm/.local/share/containers/podman/machine/machine",
        "IsMachine": true,
        "Default": false,
        "ReadWrite": true
    }
]
.EE

.PP
Show connection names and URIs:

.EX
$ podman system connection list --format "{{.Name}}\\t{{.URI}}"
podman-machine-default	ssh://core@127.0.0.1:53298/run/user/501/podman/podman.sock
podman-machine-default-root	ssh://root@127.0.0.1:53298/run/podman/podman.sock
.EE

.PP
Show all connection details in a comprehensive format:

.EX
$ podman system connection list --format "Name: {{.Name}}\\nURI: {{.URI}}\\nIdentity: {{.Identity}}\\nDefault: {{.Default}}\\nReadWrite: {{.ReadWrite}}\\n---"
Name: podman-machine-default
URI: ssh://core@127.0.0.1:53298/run/user/501/podman/podman.sock
Identity: /Users/ragm/.local/share/containers/podman/machine/machine
Default: true
ReadWrite: true
---
Name: podman-machine-default-root
URI: ssh://root@127.0.0.1:53298/run/podman/podman.sock
Identity: /Users/ragm/.local/share/containers/podman/machine/machine
Default: false
ReadWrite: true
---
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-system(1)\fP, \fBpodman-system-connection(1)\fP

.SH HISTORY
July 2020, Originally compiled by Jhon Honce (jhonce at redhat dot com)
