'\" t
.nh
.TH podman-artifact-inspect 1
.SH NAME
podman-artifact-inspect \- Inspect an OCI artifact

.SH SYNOPSIS
\fBpodman artifact inspect\fP \fIname\fP

.SH DESCRIPTION
Inspect an artifact in the local store and output the results in JSON format.
The artifact can be referred to with either:
.IP "  1." 5
Fully qualified artifact name
.IP "  2." 5
Full or partial digest of the artifact's manifest

.PP
The inspect output includes the artifact manifest with annotations. All artifacts
automatically include a creation timestamp in the \fBorg.opencontainers.image.created\fR
annotation using RFC3339Nano format, showing when the artifact was initially created.

.SH OPTIONS
.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Format the output using the given Go template.
The keys of the returned JSON can be used as the values for the --format flag (see examples below).

.PP
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Artifact ...	T{
Artifact details (nested struct)
T}
\&.Digest	T{
Artifact digest (sha256:+64-char hash)
T}
\&.Manifest ...	T{
Artifact manifest details (struct)
T}
\&.Name	Artifact name (string)
\&.TotalSizeBytes	T{
Total Size of the artifact in bytes
T}
.TE

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLES
Inspect an OCI image in the local store.

.EX
$ podman artifact inspect quay.io/myartifact/mytxt:latest
{
     "Manifest": {
          "schemaVersion": 2,
          "mediaType": "application/vnd.oci.image.manifest.v1+json",
          "config": {
               "mediaType": "application/vnd.oci.empty.v1+json",
               "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
               "size": 2,
               "data": "e30="
          },
          "layers": [
               {
                    "mediaType": "text/plain; charset=utf-8",
                    "digest": "sha256:f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2",
                    "size": 5,
                    "annotations": {
                         "org.opencontainers.image.title": "foobar.txt"
                    }
               }
          ]
     },
     "Name": "quay.io/myartifact/mytxt:latest",
     "Digest": "sha256:6c28fa07a5b0a1cee29862c1f6ea38a66df982495b14da2c052427eb628ed8c6"
}
.EE

.PP
Inspect artifact digest for the specified artifact:

.EX
$ podman artifact inspect quay.io/myartifact/mytxt:latest --format {{.Digest}}
sha256:6c28fa07a5b0a1cee29862c1f6ea38a66df982495b14da2c052427eb628ed8c6
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-artifact(1)\fP

.SH HISTORY
Sept 2024, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
