.nh
.TH podman-kube-down 1
.SH NAME
podman-kube-down \- Remove containers and pods based on Kubernetes YAML

.SH SYNOPSIS
\fBpodman kube down\fP [\fIoptions\fP] \fIfile.yml|-|https://website.io/file.yml\fP [\fIfile2.yml|https://website.io/file2.yml\fP ...]

.SH DESCRIPTION
\fBpodman kube down\fP reads one or more specified Kubernetes YAML files, tearing down pods that were created by the \fBpodman kube play\fR command via the same Kubernetes YAML
files. Any volumes that were created by the previous \fBpodman kube play\fR command remain intact unless the \fB--force\fR options is used. If the YAML file is
specified as \fB-\fR, \fBpodman kube down\fR reads the YAML from stdin. The inputs can also be URLs that point to YAML files such as https://podman.io/demo.yml.
\fBpodman kube down\fR tears down the pods and containers created by \fBpodman kube play\fR via the same Kubernetes YAML from the URLs. However,
\fBpodman kube down\fR does not work with a URL if the YAML file the URL points to has been changed or altered since the creation of the pods and containers using
\fBpodman kube play\fR\&.

.PP
When multiple YAML files are specified (local files, URLs, or a combination), they are processed sequentially and combined with YAML document separators (\fB---\fR), just like with \fBpodman kube play\fR\&.

.SH OPTIONS
.SS \fB--force\fP
Tear down the volumes linked to the PersistentVolumeClaims as part --down

.SH EXAMPLES
Example YAML file \fBdemo.yml\fR:

.EX
apiVersion: v1
kind: Pod
metadata:
\&...
spec:
  containers:
  - command:
    - top
    - name: container
      value: podman
    image: foobar
\&...
.EE

.PP
Remove the pod and containers as described in the \fBdemo.yml\fR file

.EX
$ podman kube down demo.yml
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.PP
Remove the pod and containers as described in the \fBdemo.yml\fR file YAML sent to stdin

.EX
$ cat demo.yml | podman kube play -
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.PP
Remove the pods and containers as described in the \fBdemo.yml\fR file YAML read from a URL

.EX
$ podman kube down https://podman.io/demo.yml
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.PP
\fBpodman kube down\fR does not work with a URL if the YAML file the URL points to has been changed
or altered since it was used to create the pods and containers.

.PP
Remove the pods and containers that were created from multiple YAML files

.EX
$ podman kube down pod.yml service.yml configmap.yml
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.PP
Remove the pods and containers that were created from multiple URLs

.EX
$ podman kube down https://example.com/pod.yml https://example.com/service.yml https://example.com/configmap.yml
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.PP
Remove the pods and containers that were created from a combination of local files and URLs

.EX
$ podman kube down local-pod.yml https://example.com/service.yml local-configmap.yml
Pods stopped:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
Pods removed:
52182811df2b1e73f36476003a66ec872101ea59034ac0d4d3a7b40903b955a6
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-kube(1)\fP, \fBpodman-kube-play(1)\fP, \fBpodman-kube-generate(1)\fP, \fBcontainers-certs.d(5)\fP
