.nh
.TH podman-machine-rm 1
.SH NAME
podman-machine-rm \- Remove a virtual machine

.SH SYNOPSIS
\fBpodman machine rm\fP [\fIoptions\fP] [\fIname\fP]

.SH DESCRIPTION
Remove a virtual machine and its related files.  What is actually deleted
depends on the virtual machine type.  For all virtual machines, the generated
podman system connections are deleted.  The ignition files
generated for that VM are also removed as is its image file on the filesystem.

.PP
Users get a display of what is deleted and are required to confirm unless the option \fB--force\fR
is used.

.PP
The default machine name is \fBpodman-machine-default\fR\&. If a machine name is not specified as an argument,
then \fBpodman-machine-default\fR will be removed.

.PP
Rootless only.

.SH OPTIONS
.SS \fB--force\fP, \fB-f\fP
Stop and delete without confirmation.

.SS \fB--help\fP
Print usage statement.

.SS \fB--save-ignition\fP
Do not delete the generated ignition file.

.SS \fB--save-image\fP
Do not delete the VM image.

.SH EXAMPLES
Remove the specified Podman machine.

.EX
$ podman machine rm test1

The following files will be deleted:

/home/user/.config/containers/podman/machine/qemu/test1.ign
/home/user/.local/share/containers/podman/machine/qemu/test1_fedora-coreos-33.20210315.1.0-qemu.x86_64.qcow2
/home/user/.config/containers/podman/machine/qemu/test1.json

Are you sure you want to continue? [y/N] y
.EE

.PP
Remove the specified Podman machine even if it is running.

.EX
$ podman machine rm -f test1
$
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
March 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
