.nh
.TH podman-machine-reset 1
.SH NAME
podman-machine-reset \- Reset Podman machines and environment

.SH SYNOPSIS
\fBpodman machine reset\fP [\fIoptions\fP]

.SH DESCRIPTION
Reset your Podman machine environment.  This command stops any running machines
and then removes them.  Configuration and data files are then removed.  Data files
would include machine disk images and any previously pulled cache images.  When
this command is run, all of your Podman machines will have been deleted.

.SH OPTIONS
.SS \fB--force\fP, \fB-f\fP
Reset without confirmation.

.SS \fB--help\fP
Print usage statement.

.SH EXAMPLES
.EX
$ podman machine reset
Warning: this command will delete all existing podman machines
and all of the configuration and data directories for Podman machines

The following machine(s) will be deleted:

dev
podman-machine-default

Are you sure you want to continue? [y/N] y
$
.EE

.PP
Force reset without confirmation.

.EX
$ podman machine reset --force
$
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
Feb 2024, Originally compiled by Brent Baudebbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
