'\" t
.nh
.TH podman-secret-ls 1
.SH NAME
podman-secret-ls \- List all available secrets

.SH SYNOPSIS
\fBpodman secret ls\fP [\fIoptions\fP]

.SH DESCRIPTION
Lists all the secrets that exist. The output can be formatted to a Go template using the \fB--format\fP option.

.SH OPTIONS
.SS \fB--filter\fP, \fB-f\fP=\fIfilter=value\fP
Filter output based on conditions given.
Multiple filters can be given with multiple uses of the --filter option.

.PP
Valid filters are listed below:

.TS
allbox;
l l 
l l .
\fB\fBFilter\fP\fP	\fB\fBDescription\fP\fP
name	T{
[Name] Secret name (accepts regex)
T}
id	[ID] Full or partial secret ID
.TE

.SS \fB--format\fP=\fIformat\fP
Format secret output using Go template.

.PP
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.CreatedAt	T{
When secret was created (relative timestamp, human-readable)
T}
\&.Driver	Driver name (string)
\&.ID	ID of secret
\&.Name	Name of secret
\&.UpdatedAt	T{
When secret was last updated (relative timestamp, human-readable)
T}
.TE

.SS \fB--noheading\fP, \fB-n\fP
Omit the table headings from the listing.

.SS \fB--quiet\fP, \fB-q\fP
Print secret IDs only.

.SH EXAMPLES
List all secrets.

.EX
$ podman secret ls
.EE

.PP
List the name field of all secrets.

.EX
$ podman secret ls --format "{{.Name}}"
.EE

.PP
List all secrets whose name includes the specified string.

.EX
$ podman secret ls --filter name=confidential
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-secret(1)\fP

.SH HISTORY
January 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
