'\" t
.nh
.TH podman-version 1
.SH NAME
podman-version \- Display the Podman version information

.SH SYNOPSIS
\fBpodman version\fP [\fIoptions\fP]

.SH DESCRIPTION
Shows the following information: Remote API Version, Version, Go Version, Git Commit, Build Time,
OS, and Architecture.

.SH OPTIONS
.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Change output format to "json" or a Go template.

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Client ...	Version of local podman
\&.Server ...	Version of remote podman
.TE

.PP
Each of the above fields branch deeper into further subfields
such as .Version, .APIVersion, .GoVersion, and more.

.SH Example
A sample output of the \fBversion\fR command:

.EX
$ podman version
Version:      2.0.0
API Version:  1
Go Version:   go1.14.2
Git Commit:   4520664f63c3a7f9a80227715359e20069d95542
Built:        Tue May 19 10:48:59 2020
OS/Arch:      linux/amd64
.EE

.PP
Filtering out only the version:

.EX
$ podman version --format '{{.Client.Version}}'
2.0.0
.EE

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
November 2018, Added --format flag by Tomas Tomecek ttomecek@redhat.com
\[la]mailto:ttomecek@redhat.com\[ra]
July 2017, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
