.nh
.TH podman-secret-rm 1
.SH NAME
podman-secret-rm \- Remove one or more secrets

.SH SYNOPSIS
\fBpodman secret rm\fP [\fIoptions\fP] \fIsecret\fP [...]

.SH DESCRIPTION
Removes one or more secrets.

.PP
\fBpodman secret rm\fR is safe to use on secrets that are in use by a container.
The created container has access to the secret data because secrets are
copied and mounted into the container when a container is created. If a secret is deleted and
another secret is created with the same name, the secret inside the container does not change;
the old secret value still remains.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all existing secrets.

.SS \fB--help\fP
Print usage statement.

.SS \fB--ignore\fP, \fB-i\fP
Ignore errors when specified secrets are not present.

.SH EXAMPLES
Remove secrets mysecret1 and mysecret2.

.EX
$ podman secret rm mysecret1 mysecret2
.EE

.PP
Remove all secrets

.EX
$ podman secret rm --all
3fa78977c813cca1d5b1a4570
4ee314533b16a47d0d8c6e775
.EE

.PP
Removes the specified secrets. No error is thrown if a non-existent secret is included.

.EX
$ podman secret rm --ignore mysecret1 mysecret2 non_existent_secret
9bb0cad56c4a610da8ebca0cc
3c497981215f1b5dd9ce19cde
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-secret(1)\fP

.SH HISTORY
January 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
