.nh
.TH podman-manifest-inspect 1
.SH NAME
podman-manifest-inspect \- Display a manifest list or image index

.SH SYNOPSIS
\fBpodman manifest inspect\fP [\fIoptions\fP] \fIlistnameorindexname\fP

.SH DESCRIPTION
Displays the manifest list or image index stored using the specified image name.

.SH RETURN VALUE
A formatted JSON representation of the manifest list or image index.

.SH OPTIONS
.SS \fB--authfile\fP=\fIpath\fP
Path of the authentication file. Default is \fB${XDG_RUNTIME_DIR}/containers/auth.json\fR on Linux, and \fB$HOME/.config/containers/auth.json\fR on Windows/macOS.
The file is created by \fBpodman login\fP\&. If the authorization state is not found there, \fB$HOME/.docker/config.json\fR is checked, which is set using \fBdocker login\fP\&.

.PP
Note: There is also the option to override the default path of the authentication file by setting the \fBREGISTRY_AUTH_FILE\fR environment variable. This can be done with \fBexport REGISTRY_AUTH_FILE=\fIpath\fP\fP\&.

.SS \fB--tls-verify\fP
Require HTTPS and verify certificates when contacting registries (default: \fBtrue\fP).
If explicitly set to \fBtrue\fP, TLS verification is used.
If set to \fBfalse\fP, TLS verification is not used.
If not specified, TLS verification is used unless the target registry
is listed as an insecure registry in \fBcontainers-registries.conf(5)\fP

.SH EXAMPLES
Inspect the manifest of mylist:v1.11.

.EX
podman manifest inspect mylist:v1.11
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-manifest(1)\fP
