.nh
.TH podman-machine-stop 1
.SH NAME
podman-machine-stop \- Stop a virtual machine

.SH SYNOPSIS
\fBpodman machine stop\fP [\fIname\fP]

.SH DESCRIPTION
Stops a virtual machine.

.PP
The default machine name is \fBpodman-machine-default\fR\&. If a machine name is not specified as an argument,
then \fBpodman-machine-default\fR will be stopped.

.PP
Rootless only.

.PP
Podman on MacOS and Windows requires a virtual machine. This is because containers are Linux -
containers do not run on any other OS because containers' core functionality are
tied to the Linux kernel. Podman machine must be used to manage MacOS and Windows machines,
but can be optionally used on Linux.

.PP
\fBpodman machine stop\fP stops a Linux virtual machine where containers are run.

.SH OPTIONS
.SS \fB--help\fP
Print usage statement.

.SH EXAMPLES
Stop a podman machine named myvm.

.EX
$ podman machine stop myvm
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
March 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
