.nh
.TH podman-pod-kill 1
.SH NAME
podman-pod-kill \- Kill the main process of each container in one or more pods

.SH SYNOPSIS
\fBpodman pod kill\fP [\fIoptions\fP] \fIpod\fP ...

.SH DESCRIPTION
The main process of each container inside the pods specified is sent SIGKILL, or any signal specified with option --signal.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Sends signal to all containers associated with a pod.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, use the last created pod.
Note: the last started pod can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--signal\fP, \fB-s\fP=\fBsignal\fP
Signal to send to the containers in the pod. For more information on Linux signals, refer to \fIsignal(7)\fP\&.
The default is \fBSIGKILL\fP\&.

.SH EXAMPLE
Kill pod with a given name:

.EX
podman pod kill mywebserver
.EE

.PP
Kill pod with a given ID:

.EX
podman pod kill 860a4b23
.EE

.PP
Terminate pod by sending \fBTERM\fR signal:

.EX
podman pod kill --signal TERM 860a4b23
.EE

.PP
Kill the latest pod. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines):

.EX
podman pod kill --latest
.EE

.PP
Terminate all pods by sending \fBKILL\fR signal:

.EX
podman pod kill --all
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-pod-stop(1)\fP

.SH HISTORY
July 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
