.nh
.TH podman-pod-pause 1
.SH NAME
podman-pod-pause \- Pause one or more pods

.SH SYNOPSIS
\fBpodman pod pause\fP [\fIoptions\fP] \fIpod\fP ...

.SH DESCRIPTION
Pauses all the running processes in the containers of one or more pods.  You may use pod IDs or names as input.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Pause all pods.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, pause the last created pod. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SH EXAMPLES
Pause a pod with a given name:

.EX
$ podman pod pause mywebserverpod
.EE

.PP
Pause a pod with a given ID:

.EX
$ podman pod pause 860a4b23
.EE

.PP
Pause all pods

.EX
$ podman pod pause --all
817973d45404da08f1fe393a13c8eeb0948f4a259d8835f083370b4a63cb0431
0793d692719c8ef1f983fd29d7568e817c5a8e865e2b3925201a75dce24cfe80
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-pod-unpause(1)\fP, \fBpodman-pause(1)\fP

.SH HISTORY
July 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
