'\" t
.nh
.TH podman-stop 1
.SH NAME
podman-stop \- Stop one or more running containers

.SH SYNOPSIS
\fBpodman stop\fP [\fIoptions\fP] \fIcontainer\fP ...

.PP
\fBpodman container stop\fP [\fIoptions\fP] \fIcontainer\fP ...

.SH DESCRIPTION
Stops one or more containers using container IDs or names as input. The \fB--time\fP option
specifies the number of seconds to wait before forcibly stopping the container after the stop command
is issued to the container. The default is 10 seconds. By default, containers are stopped with SIGTERM
and then SIGKILL after the timeout. The SIGTERM default can be overridden by the image used to create the
container and also via command line when creating the container.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Stop all running containers.  This does not include paused containers.

.SS \fB--cidfile\fP=\fIfile\fP
Read container ID from the specified \fIfile\fP and stop the container.
Can be specified multiple times.

.PP
Command does not fail when \fIfile\fP is missing and user specified --ignore.

.SS \fB--filter\fP, \fB-f\fP=\fIfilter\fP
Filter what containers stop.
Multiple filters can be given with multiple uses of the --filter flag.
Filters with the same key work inclusive with the only exception being
\fBlabel\fR which is exclusive. Filters with different keys always work exclusive.

.PP
Valid filters are listed below:

.TS
allbox;
l l 
l l .
\fB\fBFilter\fP\fP	\fB\fBDescription\fP\fP
id	T{
[ID] Container's ID (CID prefix match by default; accepts regex)
T}
name	T{
[Name] Container's name (accepts regex)
T}
label	T{
[Key] or [Key=Value] Label assigned to a container
T}
label!	T{
[Key] or [Key=Value] Label NOT assigned to a container
T}
exited	[Int] Container's exit code
status	T{
[Status] Container's status: 'created', 'initialized', 'exited', 'paused', 'running', 'unknown'
T}
ancestor	T{
[ImageName] Image or descendant used to create container (accepts regex)
T}
before	T{
[ID] or [Name] Containers created before this container
T}
since	T{
[ID] or [Name] Containers created since this container
T}
volume	T{
[VolumeName] or [MountpointDestination] Volume mounted in container
T}
health	[Status] healthy or unhealthy
pod	T{
[Pod] name or full or partial ID of pod
T}
network	T{
[Network] name or full ID of network
T}
restart-policy	T{
[Policy] Container's restart policy (e.g., 'no', 'on-failure', 'always', 'unless-stopped')
T}
until	T{
[DateTime] Containers created before the given duration or time.
T}
command	T{
[Command] the command the container is executing, only argv[0] is taken
T}
should-start-on-boot	T{
[Bool] Containers that need to be restarted after system reboot. True for containers with restart policy 'always', or 'unless-stopped' that were not explicitly stopped by the user
T}
.TE

.SS \fB--ignore\fP, \fB-i\fP
Ignore errors when specified containers are not in the container store.  A user
might have decided to manually remove a container which leads to a failure
during the ExecStop directive of a systemd service referencing that container.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--time\fP, \fB-t\fP=\fIseconds\fP
Seconds to wait before forcibly stopping the container.
Use -1 for infinite wait.

.SH EXAMPLES
Stop the specified container via its name.

.EX
$ podman stop mywebserver
.EE

.PP
Stop the container via its id.

.EX
$ podman stop 860a4b235279
.EE

.PP
Stop multiple containers.

.EX
$ podman stop mywebserver 860a4b235279
.EE

.PP
Stop the container identified in the cidfile.

.EX
$ podman stop --cidfile /home/user/cidfile-1
.EE

.PP
Stop the containers identified in the cidfiles.

.EX
$ podman stop --cidfile /home/user/cidfile-1 --cidfile ./cidfile-2
.EE

.PP
Stop the specified container in 2 seconds.

.EX
$ podman stop --time 2 860a4b235279
.EE

.PP
Stop all running containers.

.EX
$ podman stop -a
.EE

.PP
Stop the last created container (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.EX
$ podman stop --latest
.EE

.PP
Stop by label.

.EX
$ podman stop --filter label=app=frontend
9351ccb3ef4272532bc0c188bd4f0ddfc2b0de217732cd108259ea126b014647
.EE

.PP
Stop by name.

.EX
$ podman stop --filter name=db-replica
6c2680da61d54690718ac3aecdb04a8aad95ae353e42cc942736823bd05c8a1d
.EE

.PP
Stop by role label.

.EX
$ podman stop --filter label=role=primary
bb3ff91d969a8dc622d627e4a8d76c18bdbd417d317c5e7e66543c0b0c8ed1e8
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-rm(1)\fP

.SH HISTORY
September 2018, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
