'\" t
.nh
.TH podman-volume 1
.SH NAME
podman-volume \- Simple management tool for volumes

.SH SYNOPSIS
\fBpodman volume\fP \fIsubcommand\fP

.SH DESCRIPTION
podman volume is a set of subcommands that manage volumes.

.SH SUBCOMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
create	podman-volume-create(1)	Create a new volume.
exists	podman-volume-exists(1)	T{
Check if the given volume exists.
T}
export	podman-volume-export(1)	Export volume to external tar.
import	podman-volume-import(1)	T{
Import tarball contents into an existing podman volume.
T}
inspect	podman-volume-inspect(1)	T{
Get detailed information on one or more volumes.
T}
ls	podman-volume-ls(1)	T{
List all the available volumes.
T}
mount	podman-volume-mount(1)	Mount a volume filesystem.
prune	podman-volume-prune(1)	Remove all unused volumes.
reload	podman-volume-reload(1)	T{
Reload all volumes from volumes plugins.
T}
rm	podman-volume-rm(1)	Remove one or more volumes.
unmount	podman-volume-unmount(1)	Unmount a volume.
.TE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
November 2018, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
