'\" t
.nh
.TH podman-network-prune 1
.SH NAME
podman-network-prune \- Remove all unused networks

.SH SYNOPSIS
\fBpodman network prune\fP [\fIoptions\fP]

.SH DESCRIPTION
Remove all unused networks.  An unused network is defined by a network which
has no containers connected or configured to connect to it. It does not remove
the so-called default network which goes by the name of \fIpodman\fP\&.

.SH OPTIONS
.SS \fB--filter\fP
Provide filter values.

.PP
The \fIfilters\fP argument format is of \fBkey=value\fR\&. If there is more than one \fIfilter\fP, then pass multiple OPTIONS: \fB--filter\fP \fIfoo=bar\fP \fB--filter\fP \fIbif=baz\fP\&.

.PP
Supported filters:

.TS
allbox;
l l 
l l .
\fBFilter\fP	\fBDescription\fP
label	T{
Only remove networks, with (or without, in the case of label!=[...] is used) the specified labels.
T}
until	T{
Only remove networks created before given timestamp.
T}
.TE

.PP
The \fBlabel\fR \fIfilter\fP accepts two formats. One is the \fBlabel\fR=\fIkey\fP or \fBlabel\fR=\fIkey\fP=\fIvalue\fP, which removes networks with the specified labels. The other format is the \fBlabel!\fR=\fIkey\fP or \fBlabel!\fR=\fIkey\fP=\fIvalue\fP, which removes networks without the specified labels.

.PP
The \fBuntil\fR \fIfilter\fP can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. 10m, 1h30m) computed relative to the machine’s time.

.SS \fB--force\fP, \fB-f\fP
Do not prompt for confirmation

.SH EXAMPLE
Prune networks:

.EX
podman network prune
.EE

.PP
Prune all networks created not created in the last two hours:

.EX
podman network prune --filter until=2h
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP, \fBpodman-network-rm(1)\fP

.SH HISTORY
February 2021, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
