'\" t
.nh
.TH podman-machine-info 1
.SH NAME
podman-machine-info \- Display machine host info

.SH SYNOPSIS
\fBpodman machine info\fP

.SH DESCRIPTION
Display information pertaining to the machine host.
Rootless only, as all \fBpodman machine\fR commands can be only be used with rootless Podman.

.PP
\fINote\fP: The \fBDefaultMachine\fR field in the \fBHost\fR output does not suggest that
one can set a default podman machine via system connections. This value represents
the current active system connection associated with a podman machine. Regardless
of the default system connection, the default podman machine will always be
\fBpodman-machine-default\fR\&.

.SH OPTIONS
.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Change output format to "json" or a Go template.

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Host ...	T{
Host information for local machine
T}
\&.Version ...	Version of the machine
.TE

.SS \fB--help\fP
Print usage statement.

.SH EXAMPLES
Display default Podman machine info.

.EX
$ podman machine info
Host:
  Arch: amd64
  CurrentMachine: ""
  DefaultMachine: ""
  EventsDir: /run/user/3267/podman
  MachineConfigDir: /home/myusername/.config/containers/podman/machine/qemu
  MachineImageDir: /home/myusername/.local/share/containers/podman/machine/qemu
  MachineState: ""
  NumberOfMachines: 0
  OS: linux
  VMType: qemu
Version:
  APIVersion: 4.4.0
  Built: 1677097848
  BuiltTime: Wed Feb 22 15:30:48 2023
  GitCommit: aa196c0d5c9abd5800edf9e27587c60343a26c2b-dirty
  GoVersion: go1.20
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.0
.EE

.PP
Display default Podman machine info formatted as json.

.EX
$ podman machine info --format json
{
  "Host": {
    "Arch": "amd64",
    "CurrentMachine": "",
    "DefaultMachine": "",
    "EventsDir": "/run/user/3267/podman",
    "MachineConfigDir": "/home/myusername/.config/containers/podman/machine/qemu",
    "MachineImageDir": "/home/myusername/.local/share/containers/podman/machine/qemu",
    "MachineState": "",
    "NumberOfMachines": 0,
    "OS": "linux",
    "VMType": "qemu"
  },
  "Version": {
    "APIVersion": "4.4.0",
    "Version": "4.4.0",
    "GoVersion": "go1.20",
    "GitCommit": "aa196c0d5c9abd5800edf9e27587c60343a26c2b-dirty",
    "BuiltTime": "Wed Feb 22 15:30:48 2023",
    "Built": 1677097848,
    "OsArch": "linux/amd64",
    "Os": "linux"
  }
}
.EE

.PP
Display default Podman machine Host.Arch field.

.EX
$ podman machine info --format "{{ .Host.Arch }}"
amd64

.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
June 2022, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
