.nh
.TH podman-manifest-create 1
.SH NAME
podman-manifest-create \- Create a manifest list or image index

.SH SYNOPSIS
\fBpodman manifest create\fP [\fIoptions\fP] \fIlistnameorindexname\fP [\fIimagename\fP ...]

.SH DESCRIPTION
Creates a new manifest list and stores it as an image in local storage using
the specified name.

.PP
If additional images are specified, they are added to the newly-created list or
index.

.SH OPTIONS
.SS \fB--all\fP
If any of the images added to the new list or index are
themselves lists or indexes, add all of their contents.  By default, only one
image from such a list is added to the newly-created list or index.

.SS \fB--amend\fP, \fB-a\fP
If a manifest list named \fIlistnameorindexname\fP already exists, modify the
preexisting list instead of exiting with an error.  The contents of
\fIlistnameorindexname\fP are not modified if no *imagename*s are given.

.SS \fB--annotation\fP=\fIvalue\fP
Set an annotation on the newly-created image index.

.SS \fB--tls-verify\fP
Require HTTPS and verify certificates when contacting registries (default: \fBtrue\fP).
If explicitly set to \fBtrue\fP, TLS verification is used.
If set to \fBfalse\fP, TLS verification is not used.
If not specified, TLS verification is used unless the target registry
is listed as an insecure registry in \fBcontainers-registries.conf(5)\fP

.SH EXAMPLES
Create the specified manifest.

.EX
podman manifest create mylist:v1.11
9cfd24048d5fc80903f088f1531a21bff01172abe66effa8941a4c2308dc745f
.EE

.PP
Create the specified manifest manifest or modify it if it previously exist.

.EX
podman manifest create --amend mylist:v1.11
9cfd24048d5fc80903f088f1531a21bff01172abe66effa8941a4c2308dc745f
.EE

.PP
Create the named manifest including the specified image matching the current platform.

.EX
podman manifest create mylist:v1.11 docker://fedora
5c2bc76bfb4ba6665a7973f7e1c05ee0536b4580637f27adc9fa5a4b2bc03cf1
.EE

.PP
Create the named manifest including all images referred to with the specified image reference.

.EX
podman manifest create --all mylist:v1.11 docker://fedora
30330571e79c65288a4fca421d9aed29b0210d57294d9c2056743fdcf6e3967b
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-manifest(1)\fP
