'\" t
.nh
.TH podman-system-connection 1
.SH NAME
podman-system-connection \- Manage the destination(s) for Podman service(s)

.SH SYNOPSIS
\fBpodman system connection\fP \fIsubcommand\fP

.SH DESCRIPTION
Manage the destination(s) for Podman service(s).

.PP
The user is prompted for the ssh login password or key file passphrase as required. The \fBssh-agent\fR is supported if it is running.

.PP
Podman manages the system connection by writing and reading the \fBpodman-connections.json\fR file located under
\fB$XDG_CONFIG_HOME/containers\fR or if the env is not set it defaults to \fB$HOME/.config/containers\fR\&.
Or the \fBPODMAN_CONNECTIONS_CONF\fR environment variable can be set to a full file path which podman
will use instead.
This file is managed by the podman commands and should never be edited by users directly. To manually
configure the connections use \fBservice_destinations\fR in containers.conf.

.PP
If the ReadWrite column in the \fBpodman system connection list\fP output is set to true the connection is
stored in the \fBpodman-connections.json\fR file otherwise it is stored in containers.conf and can therefore
not be edited with the \fBpodman system connection\fP commands.

.SH COMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
add	podman-system-connection-add(1)	T{
Record destination for the Podman service
T}
default	podman-system-connection-default(1)	T{
Set named destination as default for the Podman service
T}
list	podman-system-connection-list(1)	T{
List the destination for the Podman service(s)
T}
remove	podman-system-connection-remove(1)	Delete named destination
rename	podman-system-connection-rename(1)	T{
Rename the destination for Podman service
T}
.TE

.SH EXAMPLE
List system connections:

.EX
$ podman system connection list
Name URI                                           Identity	      Default  ReadWrite
devl ssh://root@example.com/run/podman/podman.sock ~/.ssh/id_rsa  true     true
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-system(1)\fP

.SH HISTORY
June 2020, Originally compiled by Jhon Honce (jhonce at redhat dot com)
