'\" t
.nh
.TH podman-farm-list 1
.SH NAME
podman-farm-list \- List the existing farms

.SH SYNOPSIS
\fBpodman farm list\fP [\fIoptions\fP]

.PP
\fBpodman farm ls\fP [\fIoptions\fP]

.SH DESCRIPTION
List all the existing farms.

.SH OPTIONS
.SS \fB--format\fP=\fIformat\fP
Change the default output format.  This can be of a supported type like 'json' or a Go template.
Valid placeholders for the Go template listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Connections	T{
List of all system connections in the farm
T}
\&.Default	T{
Indicates whether farm is the default
T}
\&.Name	Farm name
\&.ReadWrite	T{
Indicates if this farm can be modified using the podman farm commands
T}
.TE

.SH EXAMPLE
List all farms:

.EX
$ podman farm list
Name        Connections  Default     ReadWrite
farm1       [f38 f37]    false       true
farm2       [f37]        true        true
.EE

.PP
Show farms in JSON format:

.EX
$ podman farm list --format json
[
  {
    "Name": "farm1",
    "Connections": [
      "f38",
      "f37"
    ],
    "Default": false,
    "ReadWrite": true
  },
  {
    "Name": "farm2",
    "Connections": [
      "f37"
    ],
    "Default": true,
    "ReadWrite": true
  }
]
.EE

.PP
Show only farm names:

.EX
$ podman farm list --format "{{.Name}}"
farm1
farm2
.EE

.PP
Show detailed farm information:

.EX
$ podman farm list --format "Farm: {{.Name}} (Default: {{.Default}}, ReadWrite: {{.ReadWrite}})\\nConnections: {{.Connections}}"
Farm: farm1 (Default: false, ReadWrite: true)
Connections: [f38 f37]
Farm: farm2 (Default: true, ReadWrite: true)
Connections: [f37]
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-farm(1)\fP

.SH HISTORY
July 2023, Originally compiled by Urvashi Mohnani (umohnani at redhat dot com)
