'\" t
.nh
.TH podman-machine 1
.SH NAME
podman-machine \- Manage Podman's virtual machine

.SH SYNOPSIS
\fBpodman machine\fP \fIsubcommand\fP

.SH DESCRIPTION
\fBpodman machine\fR is a set of subcommands that manage Podman's virtual machine.

.PP
Podman on MacOS and Windows requires a virtual machine. This is because containers are Linux -
containers do not run on any other OS because containers' core functionality are
tied to the Linux kernel. Podman machine must be used to manage MacOS and Windows machines,
but can be optionally used on Linux.

.PP
All \fBpodman machine\fR commands are rootless only.

.PP
NOTE: The podman-machine configuration file is managed under the
\fB$XDG_CONFIG_HOME/containers/podman/machine/\fR directory. Changing the \fB$XDG_CONFIG_HOME\fR
environment variable while the machines are running can lead to unexpected behavior.

.PP
Podman machine behaviour can be modified via the [machine] section in the containers.conf(5) file.

.SH SUBCOMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
cp	podman-machine-cp(1)	T{
Securely copy contents between the host and the virtual machine
T}
info	podman-machine-info(1)	Display machine host info
init	podman-machine-init(1)	T{
Initialize a new virtual machine
T}
inspect	podman-machine-inspect(1)	T{
Inspect one or more virtual machines
T}
list	podman-machine-list(1)	List virtual machines
os	podman-machine-os(1)	T{
Manage a Podman virtual machine's OS
T}
reset	podman-machine-reset(1)	T{
Reset Podman machines and environment
T}
rm	podman-machine-rm(1)	Remove a virtual machine
set	podman-machine-set(1)	Set a virtual machine setting
ssh	podman-machine-ssh(1)	SSH into a virtual machine
start	podman-machine-start(1)	Start a virtual machine
stop	podman-machine-stop(1)	Stop a virtual machine
.TE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine-cp(1)\fP, \fBpodman-machine-info(1)\fP, \fBpodman-machine-init(1)\fP, \fBpodman-machine-list(1)\fP, \fBpodman-machine-os(1)\fP, \fBpodman-machine-rm(1)\fP, \fBpodman-machine-ssh(1)\fP, \fBpodman-machine-start(1)\fP, \fBpodman-machine-stop(1)\fP, \fBpodman-machine-inspect(1)\fP, \fBpodman-machine-reset(1)\fP, \fBcontainers.conf(5)\fP

.SS Troubleshooting
See podman-troubleshooting(7)
for solutions to common issues.

.SH HISTORY
March 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
