'\" t
.nh
.TH podman-volume-inspect 1
.SH NAME
podman-volume-inspect \- Get detailed information on one or more volumes

.SH SYNOPSIS
\fBpodman volume inspect\fP [\fIoptions\fP] \fIvolume\fP [...]

.SH DESCRIPTION
Display detailed information on one or more volumes. The output can be formatted using
the \fB--format\fP flag and a Go template. To get detailed information about all the
existing volumes, use the \fB--all\fP flag.
Volumes can be queried individually by providing their full name or a unique partial name.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Inspect all volumes.

.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Format volume output using Go template

.PP
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.Anonymous	T{
Indicates whether volume is anonymous
T}
\&.CreatedAt ...	Volume creation time
\&.Driver	Volume driver
\&.GID	T{
GID the volume was created with
T}
\&.Labels ...	T{
Label information associated with the volume
T}
\&.LockNumber	T{
Number of the volume's Libpod lock
T}
\&.MountCount	T{
Number of times the volume is mounted
T}
\&.Mountpoint	Source of volume mount point
\&.Name	Volume name
\&.NeedsChown	T{
Indicates volume will be chowned on next use
T}
\&.NeedsCopyUp	T{
Indicates data at the destination will be copied into the volume on next use
T}
\&.Options ...	Volume options
\&.Scope	Volume scope
\&.Status ...	Status of the volume
\&.StorageID	StorageID of the volume
\&.Timeout	Timeout of the volume
\&.UID	T{
UID the volume was created with
T}
.TE

.SS \fB--help\fP
Print usage statement

.SH EXAMPLES
Inspect named volume.

.EX
$ podman volume inspect myvol
[
     {
          "Name": "myvol",
          "Driver": "local",
          "Mountpoint": "/home/myusername/.local/share/containers/storage/volumes/myvol/_data",
          "CreatedAt": "2023-03-13T16:26:48.423069028-04:00",
          "Labels": {},
          "Scope": "local",
          "Options": {},
          "MountCount": 0,
          "NeedsCopyUp": true,
          "NeedsChown": true
     }
]
.EE

.PP
Inspect all volumes.

.EX
$ podman volume inspect --all
[
     {
          "Name": "myvol",
          "Driver": "local",
          "Mountpoint": "/home/myusername/.local/share/containers/storage/volumes/myvol/_data",
          "CreatedAt": "2023-03-13T16:26:48.423069028-04:00",
          "Labels": {},
          "Scope": "local",
          "Options": {},
          "MountCount": 0,
          "NeedsCopyUp": true,
          "NeedsChown": true
     }
]
.EE

.PP
Inspect named volume and display its Driver and Scope field.

.EX
$ podman volume inspect --format "{{.Driver}} {{.Scope}}" myvol
local local
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP, \fBpodman-inspect(1)\fP

.SH HISTORY
November 2018, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
