.nh
.TH podman-network-exists 1
.SH NAME
podman-network-exists \- Check if the given network exists

.SH SYNOPSIS
\fBpodman network exists\fP \fInetwork\fP

.SH DESCRIPTION
\fBpodman network exists\fP checks if a network exists. The \fBName\fP or \fBID\fP
of the network may be used as input.  Podman returns an exit code
of \fB0\fR when the network is found.  A \fB1\fR is returned otherwise. An exit code of
\fB125\fR indicates there was another issue.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLE
Check if specified network exists (the network does actually exist):

.EX
$ podman network exists net1
$ echo $?
0
.EE

.PP
Check if nonexistent network exists:

.EX
$ podman network exists webbackend
$ echo $?
1
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP

.SH HISTORY
January 2021, Originally compiled by Paul Holzinger \fB<paul.holzinger@web.de>\fR
