'\" t
.nh
.TH podman-stats 1
.SH NAME
podman-stats \- Display a live stream of one or more container's resource usage statistics

.SH SYNOPSIS
\fBpodman stats\fP [\fIoptions\fP] [\fIcontainer\fP]

.PP
\fBpodman container stats\fP [\fIoptions\fP] [\fIcontainer\fP]

.SH DESCRIPTION
Display a live stream of one or more containers' resource usage statistics

.PP
Note:  Podman stats does not work in rootless environments that use cgroups v1.
Podman stats relies on cgroup information for statistics, and cgroup v1 is not
supported for rootless use cases.

.PP
Note: Rootless environments that use cgroups v2 are not able to report statistics
about their networking usage.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Show all containers.  Only running containers are shown by default

.SS \fB--format\fP=\fItemplate\fP
Pretty-print container statistics to JSON or using a Go template

.PP
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.AvgCPU	T{
Average CPU, full precision float
T}
\&.AVGCPU	T{
Average CPU, formatted as a percent
T}
\&.BlockInput	T{
Total data read from block device
T}
\&.BlockIO	T{
Total data read/total data written to block device
T}
\&.BlockOutput	T{
Total data written to block device
T}
\&.ContainerID	T{
Container ID, full (untruncated) hash
T}
\&.ContainerStats ...	T{
Nested structure, for experts only
T}
\&.CPU	T{
Percent CPU, full precision float
T}
\&.CPUNano	T{
CPU Usage, total, in nanoseconds
T}
\&.CPUPerc	Percentage of CPU used
\&.CPUSystemNano	T{
CPU Usage, kernel, in nanoseconds
T}
\&.Duration	Same as CPUNano
\&.ID	Container ID, truncated
\&.MemLimit	Memory limit, in bytes
\&.MemPerc	Memory percentage used
\&.MemUsage	Memory usage
\&.MemUsageBytes	Memory usage (IEC)
\&.Name	Container Name
\&.NetIO	Network IO
\&.Network ...	T{
Network I/O, separated by network interface
T}
\&.PerCPU	T{
CPU time consumed by all tasks [1]
T}
\&.PIDs	Number of PIDs
\&.PIDS	T{
Number of PIDs (yes, we know this is a dup)
T}
\&.SystemNano	T{
Current system datetime, nanoseconds since epoch
T}
\&.Up	T{
Duration (CPUNano), in human-readable form
T}
\&.UpTime	Same as Up
.TE

.PP
[1] Cgroups V1 only

.PP
When using a Go template, precede the format with \fBtable\fR to print headers.

.SS \fB--interval\fP, \fB-i\fP=\fIseconds\fP
Time in seconds between stats reports, defaults to 5 seconds.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--no-reset\fP
Do not clear the terminal/screen in between reporting intervals

.SS \fB--no-stream\fP
Disable streaming stats and only pull the first result, default setting is false

.SS \fB--no-trunc\fP
Do not truncate output

.SH EXAMPLE
List statistics about all running containers without streaming mode:

.EX
# podman stats -a --no-stream
ID             NAME              CPU %   MEM USAGE / LIMIT   MEM %   NET IO    BLOCK IO   PIDS
a9f807ffaacd   frosty_hodgkin    --      3.092MB / 16.7GB    0.02%   -- / --   -- / --    2
3b33001239ee   sleepy_stallman   --      -- / --             --      -- / --   -- / --    --
.EE

.PP
List the specified container's statistics in streaming mode:

.EX
# podman stats a9f80
ID             NAME             CPU %   MEM USAGE / LIMIT   MEM %   NET IO    BLOCK IO   PIDS
a9f807ffaacd   frosty_hodgkin   --      3.092MB / 16.7GB    0.02%   -- / --   -- / --    2
.EE

.PP
List the specified statistics about the specified container in table format:

.EX
$ podman stats --no-trunc 3667 --format 'table {{ .ID }} {{ .MemUsage }}'
ID                                                                MEM USAGE / LIMIT
3667c6aacb06aac2eaffce914c01736420023d56ef9b0f4cfe58b6d6a78b7503  49.15kB / 67.17GB
.EE

.PP
List the specified container statistics in JSON format:

.EX
# podman stats --no-stream --format=json a9f80
[
    {
	"id": "a9f807ffaacd",
	"name": "frosty_hodgkin",
	"cpu_percent": "--",
	"mem_usage": "3.092MB / 16.7GB",
	"mem_percent": "0.02%",
	"netio": "-- / --",
	"blocki": "-- / --",
	"pids": "2"
    }
]
.EE

.PP
List the specified container statistics in table format:

.EX
# podman stats --no-stream --format "table {{.ID}} {{.Name}} {{.MemUsage}}" 6eae
ID             NAME           MEM USAGE / LIMIT
6eae9e25a564   clever_bassi   3.031MB / 16.7GB
.EE

.PP
Note: When using a slirp4netns network with the rootlesskit port
handler, the traffic sent via the port forwarding is accounted to
the \fBlo\fR device.  Traffic accounted to \fBlo\fR is not accounted in the
stats output.

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
July 2017, Originally compiled by Ryan Cole rycole@redhat.com
\[la]mailto:rycole@redhat.com\[ra]
