.nh
.TH podman-pod-logs 1
.SH NAME
podman-pod-logs \- Display logs for pod with one or more containers

.SH SYNOPSIS
\fBpodman pod logs\fP [\fIoptions\fP] \fIpod\fP

.SH DESCRIPTION
The podman pod logs command batch-retrieves whatever logs are present with all the containers of a pod. Pod logs can be filtered by container name or ID using flag \fB-c\fP or \fB--container\fP if needed.

.PP
Note: A long-running \fBpodman pod log\fR command with a \fB-f\fR or \fB--follow\fR option needs to be reinvoked if a new container is added to the pod dynamically; otherwise, logs of newly added containers are not visible in the log stream.

.SH OPTIONS
.SS \fB--color\fP
Output the containers with different colors in the log.

.SS \fB--container\fP, \fB-c\fP
By default, \fBpodman pod logs\fR retrieves logs for all the containers available within the pod, differentiated by the field \fBcontainer\fR\&. However, there are use cases where the user wants to limit the log stream only to a particular container of a pod. For such cases, \fB-c\fR can be used like \fBpodman pod logs -c ctrNameorID podname\fR\&.

.SS \fB--follow\fP, \fB-f\fP
Follow log output.  Default is false.

.PP
Note: When following a pod which is removed by \fBpodman pod rm\fR
or removed on exit (\fBpodman run --rm ...\fR), there is a chance that the log
file is removed before \fBpodman pod logs\fR reads the final content.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, use the last created pod.
Note: the last started pod can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--names\fP, \fB-n\fP
Output the container names instead of the container IDs in the log.

.SS \fB--since\fP=\fITIMESTAMP\fP
Show logs since TIMESTAMP. The --since option can be Unix timestamps, date formatted timestamps, or Go duration
strings (e.g. 10m, 1h30m) computed relative to the client machine's time. Supported formats for date formatted
time stamps include RFC3339Nano, RFC3339, 2006-01-02T15:04:05, 2006-01-02T15:04:05.999999999, 2006-01-02Z07:00,
and 2006-01-02.

.SS \fB--tail\fP=\fILINES\fP
Output the specified number of LINES at the end of the logs.  LINES must be an integer.  Defaults to -1,
which prints all lines

.SS \fB--timestamps\fP, \fB-t\fP
Show timestamps in the log outputs.  The default is false

.SS \fB--until\fP=\fITIMESTAMP\fP
Show logs until TIMESTAMP. The --until option can be Unix timestamps, date formatted timestamps, or Go duration
strings (e.g. 10m, 1h30m) computed relative to the client machine's time. Supported formats for date formatted
time stamps include RFC3339Nano, RFC3339, 2006-01-02T15:04:05, 2006-01-02T15:04:05.999999999, 2006-01-02Z07:00,
and 2006-01-02.

.SH EXAMPLE
To view a pod's logs:

.EX
podman pod logs -t podIdorName
.EE

.PP
To view logs of a specific container on the pod:

.EX
podman pod logs -c ctrIdOrName podIdOrName
.EE

.PP
To view all pod logs:

.EX
podman pod logs -t --since 0 myserver-pod-1
.EE

.PP
To view a pod's logs since a certain time:

.EX
podman pod logs -t --since 2017-08-07T10:10:09.055837383-04:00 myserver-pod-1
.EE

.PP
To view a pod's logs generated in the last 10 minutes:

.EX
podman pod logs --since 10m myserver-pod-1
.EE

.PP
To view a pod's logs until 30 minutes ago:

.EX
podman pod logs --until 30m myserver-pod-1
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-pod-rm(1)\fP, \fBpodman-logs(1)\fP
