'\" t
.nh
.TH podman-secret 1
.SH NAME
podman-secret \- Manage podman secrets

.SH SYNOPSIS
\fBpodman secret\fP \fIsubcommand\fP

.SH DESCRIPTION
podman secret is a set of subcommands that manage secrets.

.SH SUBCOMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
create	podman-secret-create(1)	Create a new secret
exists	podman-secret-exists(1)	T{
Check if the given secret exists
T}
inspect	podman-secret-inspect(1)	T{
Display detailed information on one or more secrets
T}
ls	podman-secret-ls(1)	List all available secrets
rm	podman-secret-rm(1)	Remove one or more secrets
.TE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
January 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
