.nh
.TH podman-pod-rm 1
.SH NAME
podman-pod-rm \- Remove one or more stopped pods and containers

.SH SYNOPSIS
\fBpodman pod rm\fP [\fIoptions\fP] \fIpod\fP

.SH DESCRIPTION
\fBpodman pod rm\fP removes one or more stopped pods and their containers from the host.  The pod name or ID can be used. The -f option stops all containers and then removes them before removing the pod. If all containers added by the user are in an exited state, the pod is removed.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all pods.  Can be used in conjunction with -f as well.

.SS \fB--force\fP, \fB-f\fP
Stop running containers and delete all stopped containers before removal of pod.

.SS \fB--ignore\fP, \fB-i\fP
Ignore errors when specified pods are not in the container store.  A user
might have decided to manually remove a pod which leads to a failure
during the ExecStop directive of a systemd service referencing that pod.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, use the last created pod.
Note: the last started pod can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--pod-id-file\fP=\fIfile\fP
Read pod ID from the specified \fIfile\fP and rm the pod. Can be specified multiple times.

.PP
If specified, the pod-id-file is removed along with the pod.

.SS \fB--time\fP, \fB-t\fP=\fIseconds\fP
Seconds to wait before forcibly stopping running containers within the pod.
Use -1 for infinite wait.

.PP
The --force option must be specified to use the --time option.

.SH EXAMPLE
Remove pod with a given name:

.EX
podman pod rm mywebserverpod
.EE

.PP
Remove multiple pods with given names and/or IDs:

.EX
podman pod rm mywebserverpod myflaskserverpod 860a4b23
.EE

.PP
Forcefully remove pod with a given ID:

.EX
podman pod rm -f 860a4b23
.EE

.PP
Forcefully remove all pods:

.EX
podman pod rm -f -a
podman pod rm -fa
.EE

.PP
Remove pod using ID specified in a given file:

.EX
podman pod rm --pod-id-file /path/to/id/file
.EE

.SH Exit Status
\fB0\fP   All specified pods removed

.PP
\fB1\fP   One of the specified pods did not exist, and no other failures

.PP
\fB2\fP   One of the specified pods is attached to a container

.PP
\fB125\fP The command fails for any other reason

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP

.SH HISTORY
July 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
