.nh
.TH podman-kill 1
.SH NAME
podman-kill \- Kill the main process in one or more containers

.SH SYNOPSIS
\fBpodman kill\fP [\fIoptions\fP] [\fIcontainer\fP ...]

.PP
\fBpodman container kill\fP [\fIoptions\fP] [\fIcontainer\fP ...]

.SH DESCRIPTION
The main process inside each container specified is sent SIGKILL or any signal specified with the \fB--signal\fR option.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Signal all running and paused containers.

.SS \fB--cidfile\fP=\fIfile\fP
Read container ID from the specified \fIfile\fP and kill the container.
Can be specified multiple times.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SS \fB--signal\fP, \fB-s\fP=\fBsignal\fP
Signal to send to the container. For more information on Linux signals, refer to \fIsignal(7)\fP\&.
The default is \fBSIGKILL\fP\&.

.SH EXAMPLE
Kill container with a given name:

.EX
podman kill mywebserver
.EE

.PP
Kill container with a given ID:

.EX
podman kill 860a4b23
.EE

.PP
Terminate container by sending \fBTERM\fR signal:

.EX
podman kill --signal TERM 860a4b23
.EE

.PP
Kill the latest container. (This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines):

.EX
podman kill --latest
.EE

.PP
Terminate all containers by sending \fBKILL\fR signal:

.EX
podman kill --signal KILL -a
.EE

.PP
Kill containers using ID specified in a given files:

.EX
podman kill --cidfile /home/user/cidfile-1
podman kill --cidfile /home/user/cidfile-1 --cidfile ./cidfile-2
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-stop(1)\fP

.SH HISTORY
September 2017, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
