.nh
.TH podman-port 1
.SH NAME
podman-port \- List port mappings for a container

.SH SYNOPSIS
\fBpodman port\fP [\fIoptions\fP] \fIcontainer\fP [\fIprivate-port\fP[/\fIproto\fP]]

.PP
\fBpodman container port\fP [\fIoptions\fP] \fIcontainer\fP [\fIprivate-port\fP[/\fIproto\fP]]

.SH DESCRIPTION
List port mappings for the \fIcontainer\fP or look up the public-facing port that is NAT-ed to the \fIprivate-port\fP\&.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
List all known port mappings for running containers; when using this option, container names or private ports/protocols filters cannot be used.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SH EXAMPLE
List all port mappings:

.EX
# podman port -a
b4d2f05432e482e017b1a4b2eae15fa7b4f6fb7e9f65c1bde46294fdef285906
80/udp -> 0.0.0.0:44327
80/tcp -> 0.0.0.0:44327
#
.EE

.PP
List port mappings for a specific container:

.EX
# podman port b4d2f054
80/udp -> 0.0.0.0:44327
80/tcp -> 0.0.0.0:44327
#
.EE

.PP
List the specified port mappings for a specific container:

.EX
# podman port b4d2f054 80
 0.0.0.0:44327
#
.EE

.PP
List the port mappings for a specific container for port 80 and the tcp protocol:

.EX
# podman port b4d2f054 80/tcp
0.0.0.0:44327
#
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-inspect(1)\fP

.SH HISTORY
January 2018, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
