.nh
.TH podman-artifact-rm 1
.SH NAME
podman-artifact-rm \- Remove one or more OCI artifacts from local storage

.SH SYNOPSIS
\fBpodman artifact rm\fP [\fIoptions\fP] \fIname\fP

.SH DESCRIPTION
Remove one or more artifacts from the local artifact store.  The input may be the fully
qualified artifact name or a full or partial artifact digest.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all artifacts in the local store.  The use of this option conflicts with
providing a name or digest of the artifact.

.SS \fB--help\fP
Print usage statement.

.SS \fB--ignore\fP, \fB-i\fP
Remove artifacts in the local store, ignoring errors when trying to remove artifacts that do not exist.

.SH EXAMPLES
Remove an artifact by name.

.EX
$ podman artifact rm quay.io/artifact/foobar2:test
Deleted: e7b417f49fc24fc7ead6485da0ebd5bc4419d8a3f394c169fee5a6f38faa4056
.EE

.PP
Remove multiple artifacts by their shortened IDs.

.EX
$ podman artifact rm c4dfb1609ee2 93fd78260bd1 c0ed59d05ff7
.EE

.PP
Remove an artifact by partial digest.

.EX
$ podman artifact rm e7b417f49fc
Deleted: e7b417f49fc24fc7ead6485da0ebd5bc4419d8a3f394c169fee5a6f38faa4056
.EE

.PP
Remove all artifacts in local storage.

.EX
$ podman artifact rm -a
Deleted: cee15f7c5ce3e86ae6ce60d84bebdc37ad34acfa9a2611cf47501469ac83a1ab
Deleted: 72875f8f6f78d5b8ba98b2dd2c0a6f395fde8f05ff63a1df580d7a88f5afa97b
.EE

.PP
Remove artifacts ignoring the errors if the artifact does not exist.

.EX
$ podman artifact rm -i 3f78d5b8ba98b2
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-artifact(1)\fP

.SH HISTORY
Jan 2025, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
