'\" t
.nh
.TH podman-container-diff 1
.SH NAME
podman-container-diff \- Inspect changes on a container's filesystem

.SH SYNOPSIS
\fBpodman container diff\fP [\fIoptions\fP] \fIcontainer\fP [\fIcontainer\fP]

.SH DESCRIPTION
Displays changes on a container's filesystem. The container is compared to its parent layer or the second argument when given.

.PP
The output is prefixed with the following symbols:

.TS
allbox;
l l 
l l .
\fBSymbol\fP	\fBDescription\fP
A	A file or directory was added.
D	T{
A file or directory was deleted.
T}
C	T{
A file or directory was changed.
T}
.TE

.SH OPTIONS
.SS \fB--format\fP
Alter the output into a different format. The only valid format for \fBpodman container diff\fP is \fBjson\fR\&.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SH EXAMPLES
.EX
# podman container diff container1
C /usr
C /usr/local
C /usr/local/bin
A /usr/local/bin/docker-entrypoint.sh
.EE

.EX
$ podman container diff --format json container1 container2
{
     "added": [
          "/test"
     ]
}
.EE

.EX
$ podman container diff --latest
C /etc
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-container(1)\fP

.SH HISTORY
July 2021, Originally compiled by Paul Holzinger pholzing@redhat.com
\[la]mailto:pholzing@redhat.com\[ra]
