.nh
.TH podman-compose 1
.SH NAME
podman-compose \- Run Compose workloads via an external compose provider

.SH SYNOPSIS
\fBpodman compose\fP [\fIoptions\fP] [\fIcommand\fP [\fIarg\fP ...]]

.SH DESCRIPTION
\fBpodman compose\fP is a thin wrapper around an external compose provider such as docker-compose or podman-compose.  This means that \fBpodman compose\fR is executing another tool that implements the compose functionality but sets up the environment in a way to let the compose provider communicate transparently with the local Podman socket.  The specified options as well as the command and argument are passed directly to the compose provider.

.PP
The default compose providers are \fBdocker-compose\fR and \fBpodman-compose\fR\&.  If installed, \fBdocker-compose\fR takes precedence since it is the original implementation of the Compose specification and is widely used on the supported platforms (i.e., Linux, Mac OS, Windows).

.PP
If you want to change the default behavior or have a custom installation path for your provider of choice, please change the \fBcompose_providers\fR field in \fBcontainers.conf(5)\fR to \fBcompose_providers = ["/path/to/provider"]\fR\&. You may also set the \fBPODMAN_COMPOSE_PROVIDER\fR environment variable.

.PP
By default, \fBpodman compose\fR will emit a warning saying that it executes an external command. This warning can be disabled by setting \fBcompose_warning_logs\fR to false in \fBcontainers.conf(5)\fR or setting the \fBPODMAN_COMPOSE_WARNING_LOGS\fR environment variable to false. See the man page for \fBcontainers.conf(5)\fR for more information.

.SH OPTIONS
To see supported options of the installed compose provider, please run \fBpodman compose --help\fR\&.

.SH SEE ALSO
\fBpodman(1)\fP, \fBcontainers.conf(5)\fP
