.nh
.TH podman-system-check 1
.SH NAME
podman-system-check \- Perform consistency checks on image and container storage

.SH SYNOPSIS
\fBpodman system check\fP [\fIoptions\fP]

.SH DESCRIPTION
Perform consistency checks on image and container storage, reporting images and
containers which have identified issues.

.SH OPTIONS
.SS \fB--force\fP, \fB-f\fP
When attempting to remove damaged images, also remove containers which depend
on those images.  By default, damaged images which are being used by containers
are left alone.

.PP
Containers which depend on damaged images do so regardless of which engine
created them, but because podman only "knows" how to shut down containers that
it started, the effect on still-running containers which were started by other
engines is difficult to predict.

.SS \fB--max\fP, \fB-m\fP=\fIduration\fP
When considering layers which are not used by any images or containers, assume
that any layers which are more than \fIduration\fP old are the results of canceled
attempts to pull images, and should be treated as though they are damaged.

.SS \fB--quick\fP, \fB-q\fP
Skip checks which are known to be time-consuming.  This will prevent some types
of errors from being detected.

.PP
The exact checks performed by this option are subject to change.

.SS \fB--repair\fP, \fB-r\fP
Remove any images which are determined to have been damaged in some way, unless
they are in use by containers.  Use \fB--force\fP to remove containers which
depend on damaged images, and those damaged images, as well.

.SH EXAMPLE
A reasonably quick check:

.EX
podman system check --quick --repair --force
.EE

.PP
A more thorough check:

.EX
podman system check --repair --max=1h --force
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-system(1)\fP

.SH HISTORY
April 2024
