.nh
.TH podman-volume-export 1
.SH NAME
podman-volume-export \- Export volume to external tar

.SH SYNOPSIS
\fBpodman volume export\fP [\fIoptions\fP] \fIvolume\fP

.SH DESCRIPTION
\fBpodman volume export\fP exports the contents of a podman volume and saves it as a tarball
on the local machine. \fBpodman volume export\fP writes to STDOUT by default and can be
redirected to a file using the \fB--output\fR flag.

.PP
\fBpodman volume export [OPTIONS] VOLUME\fP

.SH OPTIONS
.SS \fB--help\fP
Print usage statement

.SS \fB--output\fP, \fB-o\fP=\fIfile\fP
Write to a file, default is STDOUT

.SH EXAMPLES
Export named volume content into the specified file.

.EX
$ podman volume export myvol --output myvol.tar

.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP, \fBpodman-volume-import(1)\fP
