.nh
.TH podman-farm-update 1
.SH NAME
podman-farm-update \- Update an existing farm

.SH SYNOPSIS
\fBpodman farm update\fP [\fIoptions\fP] \fIname\fP

.SH DESCRIPTION
Update a farm by either adding connections to it, removing connections from it, or setting it as the new
default farm.

.SH OPTIONS
.SS \fB--add\fP, \fB-a\fP
Add new connections to an existing farm. Multiple connections can be added at once.

.SS \fB--default\fP, \fB-d\fP
Set the current farm as the default.

.SS \fB--remove\fP, \fB-r\fP
Remove one or more connections from an existing farm.

.SH EXAMPLE
Add two connections to specified farm:

.EX
$ podman farm update --add f35,f38 farm1
.EE

.PP
Add connection to specified farm:

.EX
$ podman farm update --remove f35 farm1
.EE

.PP
Change specified farm to be default:

.EX
$ podman farm update --default farm2
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-farm(1)\fP

.SH HISTORY
July 2023, Originally compiled by Urvashi Mohnani (umohnani at redhat dot com)s
