'\" t
.nh
.TH podman-save 1
.SH NAME
podman-save \- Save image(s) to an archive

.SH SYNOPSIS
\fBpodman save\fP [\fIoptions\fP] \fIname\fP[:\fItag\fP]

.PP
\fBpodman image save\fP [\fIoptions\fP] \fIname\fP[:\fItag\fP]

.SH DESCRIPTION
\fBpodman save\fP saves an image to a local file or directory.
\fBpodman save\fP writes to STDOUT by default and can be redirected to a
file using the \fBoutput\fP flag. The \fBquiet\fP flag suppresses the output when set.
\fBpodman save\fP saves parent layers of the image(s) and the image(s) can be loaded using \fBpodman load\fP\&.
To export the containers, use the \fBpodman export\fP\&.
Note: \fB:\fR is a restricted character and cannot be part of the file name.

.SH OPTIONS
.SS \fB--compress\fP
Compress tarball image layers when pushing to a directory using the 'dir' transport. (default is same compression type, compressed or uncompressed, as source)

.PP
Note: This flag can only be set with \fB--format=docker-dir\fP\&.

.SS \fB--format\fP=\fIformat\fP
An image format to produce, one of:

.TS
allbox;
l l 
l l .
\fBFormat\fP	\fBDescription\fP
\fBdocker-archive\fP	T{
A tar archive interoperable with \fBdocker load(1)\fP (the default)
T}
\fBoci-archive\fP	T{
A tar archive using the OCI Image Format
T}
\fBoci-dir\fP	T{
A directory using the OCI Image Format
T}
\fBdocker-dir\fP	\fBdir\fP transport (see \fBcontainers-transports(5)\fP) with v2s2 manifest type
.TE

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--multi-image-archive\fP, \fB-m\fP
Allow for creating archives with more than one image.  Additional names are interpreted as images instead of tags.  Only supported for \fB--format=docker-archive\fP\&.
The default for this option can be modified via the \fBmulti_image_archive="true"|"false"\fR flag in containers.conf.

.SS \fB--output\fP, \fB-o\fP=\fIfile\fP
Write to a file, default is STDOUT

.SS \fB--quiet\fP, \fB-q\fP
Suppress the output

.SS \fB--uncompressed\fP
Accept uncompressed layers when using one of the OCI formats.

.SH EXAMPLES
Save image to a local file without displaying progress.

.EX
$ podman save --quiet -o alpine.tar alpine:2.6
.EE

.PP
Save image to stdout and redirect content via shell.

.EX
$ podman save alpine > alpine-all.tar
.EE

.PP
Save image in oci-archive format to the local file.

.EX
$ podman save -o oci-alpine.tar --format oci-archive alpine
.EE

.PP
Save image compressed in docker-dir format.

.EX
$ podman save --compress --format docker-dir -o alp-dir alpine
Getting image source signatures
Copying blob sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d
 1.97 MB / 1.97 MB [========================================================] 0s
Copying config sha256:501d1a8f0487e93128df34ea349795bc324d5e0c0d5112e08386a9dfaff620be
 584 B / 584 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-load(1)\fP, \fBcontainers.conf(5)\fP, \fBcontainers-transports(5)\fP

.SH HISTORY
July 2017, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
