.nh
.TH podman-wait 1
.SH NAME
podman-wait \- Wait on one or more containers to stop and print their exit codes

.SH SYNOPSIS
\fBpodman wait\fP [\fIoptions\fP] \fIcontainer\fP [...]

.PP
\fBpodman container wait\fP [\fIoptions\fP] \fIcontainer\fP [...]

.SH DESCRIPTION
Waits on one or more containers to stop.  The container can be referred to by its
name or ID.  In the case of multiple containers, Podman waits on each consecutively.
After all conditions are satisfied, the containers' return codes are printed
separated by newline in the same order as they were given to the command.  An
exit code of -1 is emitted for all conditions other than "stopped" and
"exited".

.PP
When waiting for containers with a restart policy of \fBalways\fR or \fBon-failure\fR,
such as those created by \fBpodman kube play\fR, the containers may be repeatedly
exiting and restarting, possibly with different exit codes. \fBpodman wait\fR will
only display and detect the first exit after the wait command was started.

.PP
When running a container with podman run --rm wait does not wait for the
container to be fully removed. To wait for the removal of a container use
\fB--condition=removing\fR\&.

.SH OPTIONS
.SS \fB--condition\fP=\fIstate\fP
Container state or condition to wait for.  Can be specified multiple times where at least one condition must match for the command to return.  Supported values are "configured", "created", "exited", "healthy", "initialized", "paused", "removing", "running", "stopped",  "stopping", "unhealthy".  The default condition is "stopped".

.SS \fB--exit-first-match\fP
Wait for exit of first container which matches conditions, ignore other ones.

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--ignore\fP
Ignore errors when a specified container is missing and mark its return code as -1.

.SS \fB--interval\fP, \fB-i\fP=\fIduration\fP
Time interval to wait before polling for completion. A duration string is a sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h". Time unit defaults to "ms".

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the container name or ID, use the last created container.
Note: the last started container can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SH EXAMPLES
Wait for the specified container to exit.

.EX
$ podman wait mywebserver
0
.EE

.PP
Wait for the latest container to exit. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.EX
$ podman wait --latest
0
.EE

.PP
Wait for the container to exit, checking every two seconds.

.EX
$ podman wait --interval 2s mywebserver
0
.EE

.PP
Wait for the container by ID. This container exits with error status 1:

.EX
$ podman wait 860a4b23
1
.EE

.PP
Wait for both specified containers to exit.

.EX
$ podman wait mywebserver myftpserver
0
125
.EE

.PP
Wait for the named container to exit, but do not fail if the container does not exist.

.EX
$ podman wait --ignore does-not-exist
-1
.EE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
September 2017, Originally compiled by Brent Baudebbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
