.nh
.TH podman-volume-exists 1
.SH NAME
podman-volume-exists \- Check if the given volume exists

.SH SYNOPSIS
\fBpodman volume exists\fP \fIvolume\fP

.SH DESCRIPTION
\fBpodman volume exists\fP checks if a volume exists. Podman returns an exit code
of \fB0\fR when the volume is found. A \fB1\fR is returned otherwise. An exit code of
\fB125\fR indicates there was another issue.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLE
Check if a volume called \fBmyvol\fR exists (the volume does actually exist).

.EX
$ podman volume exists myvol
$ echo $?
0
$
.EE

.PP
Check if a volume called \fBmysql\fR exists (the volume does not actually exist).

.EX
$ podman volume exists mysql
$ echo $?
1
$
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP

.SH HISTORY
January 2021, Originally compiled by Paul Holzinger \fB<paul.holzinger@web.de>\fR
