.nh
.TH podman-network-update 1
.SH NAME
podman-network-update \- Update an existing Podman network

.SH SYNOPSIS
\fBpodman network update\fP  [\fIoptions\fP] \fInetwork\fP

.SH DESCRIPTION
Allow changes to existing container networks. At present, only changes to the DNS servers in use by a network is supported.

.PP
NOTE: Only supported with the netavark network backend.

.SH OPTIONS
.SS \fB--dns-add\fP
Accepts array of DNS resolvers and add it to the existing list of resolvers configured for a network.

.SS \fB--dns-drop\fP
Accepts array of DNS resolvers and removes them from the existing list of resolvers configured for a network.

.SH EXAMPLE
Update a network:

.EX
$ podman network update network1 --dns-add 8.8.8.8,1.1.1.1
.EE

.PP
Update a network and add/remove dns servers:

.EX
$ podman network update network1 --dns-drop 8.8.8.8 --dns-add 3.3.3.3
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP, \fBpodman-network-inspect(1)\fP, \fBpodman-network-ls(1)\fP
