'\" t
.nh
.TH podman-image-diff 1
.SH NAME
podman-image-diff \- Inspect changes on an image's filesystem

.SH SYNOPSIS
\fBpodman image diff\fP [\fIoptions\fP] \fIimage\fP [\fIimage\fP]

.SH DESCRIPTION
Displays changes on an image's filesystem.  The image is compared to its parent layer or the second argument when given.

.PP
The output is prefixed with the following symbols:

.TS
allbox;
l l 
l l .
\fBSymbol\fP	\fBDescription\fP
A	A file or directory was added.
D	T{
A file or directory was deleted.
T}
C	T{
A file or directory was changed.
T}
.TE

.SH OPTIONS
.SS \fB--format\fP
Alter the output into a different format.  The only valid format for \fBpodman image diff\fP is \fBjson\fR\&.

.SH EXAMPLES
Display image differences from images parent layer:

.EX
$ podman image diff redis:old
C /usr
C /usr/local
C /usr/local/bin
A /usr/local/bin/docker-entrypoint.sh
.EE

.PP
Display image differences between two different images in JSON format:

.EX
$ podman image diff --format json redis:old redis:alpine
{
  "changed": [
    "/usr",
    "/usr/local",
    "/usr/local/bin"
  ],
  "added": [
    "/usr/local/bin/docker-entrypoint.sh"
  ]
}
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-image(1)\fP

.SH HISTORY
August 2017, Originally compiled by Ryan Cole rycole@redhat.com
\[la]mailto:rycole@redhat.com\[ra]
