.nh
.TH podman-system-connection-remove 1
.SH NAME
podman-system-connection-remove \- Delete named destination

.SH SYNOPSIS
\fBpodman system connection remove\fP [\fIoptions\fP] \fIname\fP

.SH DESCRIPTION
Delete named ssh destination.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all connections.

.SH EXAMPLE
Remove the specified system connection:

.EX
$ podman system connection remove production
.EE

.PP
Remove all system connections:

.EX
$ podman system connection remove --all
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-system(1)\fP, \fBpodman-system-connection(1)\fP

.SH HISTORY
July 2020, Originally compiled by Jhon Honce (jhonce at redhat dot com)
