.nh
.TH podman-pod-unpause 1
.SH NAME
podman-pod-unpause \- Unpause one or more pods

.SH SYNOPSIS
\fBpodman pod unpause\fP [\fIoptions\fP] \fIpod\fP ...

.SH DESCRIPTION
Unpauses all the paused processes in the containers of one or more pods.  You may use pod IDs or names as input.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Unpause all pods.

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, unpause the last created pod. (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.SH EXAMPLE
Unpause pod with a given name:

.EX
podman pod unpause mywebserverpod
.EE

.PP
Unpause pod with a given ID:

.EX
podman pod unpause 860a4b23
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-pod-pause(1)\fP

.SH HISTORY
July 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
