.nh
.TH podman-tag 1
.SH NAME
podman-tag \- Add an additional name to a local image

.SH SYNOPSIS
\fBpodman tag\fP \fIimage\fP[:\fItag\fP] [\fItarget-name\fP[:\fItag\fP]...] [\fIoptions\fP]

.PP
\fBpodman image tag\fP \fIimage\fP[:\fItag\fP] [\fItarget-name\fP[:\fItag\fP]...] [\fIoptions\fP]

.SH DESCRIPTION
Assigns a new image name to an existing image.  A full name refers to the entire
image name, including the optional \fItag\fP after the \fB:\fR\&.  If there is no \fItag\fP
provided, then Podman defaults to \fBlatest\fR for both the \fIimage\fP and the
\fItarget-name\fP\&.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLES
Tag specified image with an image name defaulting to :latest.

.EX
$ podman tag 0e3bbc2 fedora:latest
.EE

.PP
Tag specified image with fully specified image name.

.EX
$ podman tag httpd myregistryhost:5000/fedora/httpd:v2
.EE

.PP
Tag specified image with multiple tags.

.EX
$ podman tag mymariadb mycontainerregistry.io/namespace/mariadb:10 mycontainerregistry.io/namespace/mariadb:10.11 mycontainerregistry.io/namespace/mariadb:10.11.12
.EE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
December 2019, Update description to refer to 'name' instead of 'alias' by Sascha Grunert sgrunert@suse.com
\[la]mailto:sgrunert@suse.com\[ra]
July 2017, Originally compiled by Ryan Cole rycole@redhat.com
\[la]mailto:rycole@redhat.com\[ra]
