'\" t
.nh
.TH podman-pod 1
.SH NAME
podman-pod \- Management tool for groups of containers, called pods

.SH SYNOPSIS
\fBpodman pod\fP \fIsubcommand\fP

.SH DESCRIPTION
podman pod is a set of subcommands that manage pods, or groups of containers.

.SH SUBCOMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
clone	podman-pod-clone(1)	T{
Create a copy of an existing pod.
T}
create	podman-pod-create(1)	Create a new pod.
exists	podman-pod-exists(1)	T{
Check if a pod exists in local storage.
T}
inspect	podman-pod-inspect(1)	T{
Display information describing a pod.
T}
kill	podman-pod-kill(1)	T{
Kill the main process of each container in one or more pods.
T}
logs	podman-pod-logs(1)	T{
Display logs for pod with one or more containers.
T}
pause	podman-pod-pause(1)	Pause one or more pods.
prune	podman-pod-prune(1)	T{
Remove all stopped pods and their containers.
T}
ps	podman-pod-ps(1)	T{
Print out information about pods.
T}
restart	podman-pod-restart(1)	Restart one or more pods.
rm	podman-pod-rm(1)	T{
Remove one or more stopped pods and containers.
T}
start	podman-pod-start(1)	Start one or more pods.
stats	podman-pod-stats(1)	T{
Display a live stream of resource usage stats for containers in one or more pods.
T}
stop	podman-pod-stop(1)	Stop one or more pods.
top	podman-pod-top(1)	T{
Display the running processes of containers in a pod.
T}
unpause	podman-pod-unpause(1)	Unpause one or more pods.
.TE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
July 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
