'\" t
.nh
.TH podman-container 1
.SH NAME
podman-container \- Manage containers

.SH SYNOPSIS
\fBpodman container\fP \fIsubcommand\fP

.SH DESCRIPTION
The container command allows management of containers

.SH COMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
attach	podman-attach(1)	Attach to a running container.
checkpoint	podman-container-checkpoint(1)	T{
Checkpoint one or more running containers.
T}
cleanup	podman-container-cleanup(1)	T{
Clean up the container's network and mountpoints.
T}
clone	podman-container-clone(1)	T{
Create a copy of an existing container.
T}
commit	podman-commit(1)	T{
Create new image based on the changed container.
T}
cp	podman-cp(1)	T{
Copy files/folders between a container and the local filesystem.
T}
create	podman-create(1)	Create a new container.
diff	podman-container-diff(1)	T{
Inspect changes on a container's filesystem
T}
exec	podman-exec(1)	T{
Execute a command in a running container.
T}
exists	podman-container-exists(1)	T{
Check if a container exists in local storage
T}
export	podman-export(1)	T{
Export a container's filesystem contents as a tar archive.
T}
init	podman-init(1)	Initialize a container
inspect	podman-container-inspect(1)	T{
Display a container's configuration.
T}
kill	podman-kill(1)	T{
Kill the main process in one or more containers.
T}
list	podman-ps(1)	T{
List the containers on the system.(alias ls)
T}
logs	podman-logs(1)	T{
Display the logs of a container.
T}
mount	podman-mount(1)	T{
Mount a working container's root filesystem.
T}
pause	podman-pause(1)	Pause one or more containers.
port	podman-port(1)	T{
List port mappings for the container.
T}
prune	podman-container-prune(1)	T{
Remove all stopped containers from local storage.
T}
ps	podman-ps(1)	T{
Print out information about containers.
T}
rename	podman-rename(1)	Rename an existing container.
restart	podman-restart(1)	T{
Restart one or more containers.
T}
restore	podman-container-restore(1)	T{
Restore one or more containers from a checkpoint.
T}
rm	podman-rm(1)	Remove one or more containers.
run	podman-run(1)	Run a command in a container.
runlabel	podman-container-runlabel(1)	T{
Execute a command as described by a container-image label.
T}
start	podman-start(1)	Start one or more containers.
stats	podman-stats(1)	T{
Display a live stream of one or more container's resource usage statistics.
T}
stop	podman-stop(1)	T{
Stop one or more running containers.
T}
top	podman-top(1)	T{
Display the running processes of a container.
T}
unmount	podman-unmount(1)	T{
Unmount a working container's root filesystem.(Alias unmount)
T}
unpause	podman-unpause(1)	T{
Unpause one or more containers.
T}
update	podman-update(1)	T{
Update the cgroup configuration of a given container.
T}
wait	podman-wait(1)	T{
Wait on one or more containers to stop and print their exit codes.
T}
.TE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-exec(1)\fP, \fBpodman-run(1)\fP
