.nh
.TH podman-secret-exists 1
.SH NAME
podman-secret-exists \- Check if the given secret exists

.SH SYNOPSIS
\fBpodman secret exists\fP \fIsecret\fP

.SH DESCRIPTION
\fBpodman secret exists\fP checks if a secret exists. Podman returns an exit code
of \fB0\fR when the secret is found. A \fB1\fR is returned otherwise. An exit code of
\fB125\fR indicates there was another issue.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLE
Check if a secret called \fBmysecret\fR exists (the secret does actually exist).

.EX
$ podman secret exists mysecret
$ echo $?
0
$
.EE

.PP
Check if a secret called \fBmypassword\fR exists (the secret does not actually exist).

.EX
$ podman secret exists mypassword
$ echo $?
1
$
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-secret(1)\fP

.SH HISTORY
April 2023, Originally compiled by Ygal Blum \fB<ygal.blum@gmail.com>\fR
