.nh
.TH podman-volume-reload 1
.SH NAME
podman-volume-reload \- Reload all volumes from volumes plugins

.SH SYNOPSIS
\fBpodman volume reload\fP

.SH DESCRIPTION
\fBpodman volume reload\fP checks all configured volume plugins and updates the libpod database with all available volumes.
Existing volumes are also removed from the database when they are no longer present in the plugin.

.PP
This command it is best effort and cannot guarantee a perfect state because plugins can be modified from the outside at any time.

.PP
Note: This command is not supported with podman-remote.

.SH EXAMPLES
Reload the volume plugins.

.EX
$ podman volume reload
Added:
vol6
Removed:
t3
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP
