.nh
.TH podman-farm-remove 1
.SH NAME
podman-farm-remove \- Delete one or more farms

.SH SYNOPSIS
\fBpodman farm remove\fP [\fIoptions\fP] \fIname\fP

.PP
\fBpodman farm rm\fP [\fIoptions\fP] \fIname\fP

.SH DESCRIPTION
Delete one or more farms.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove all farms.

.SH EXAMPLE
Remove specified farm:

.EX
$ podman farm remove farm1
.EE

.PP
Remove all farms:

.EX
$ podman farm rm --all
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-farm(1)\fP

.SH HISTORY
July 2023, Originally compiled by Urvashi Mohnani (umohnani at redhat dot com)s
