.nh
.TH podman-artifact-add 1
.SH NAME
podman-artifact-add \- Add an OCI artifact to local artifact store

.SH SYNOPSIS
\fBpodman artifact add\fP [\fIoptions\fP] \fIartifact-name\fP \fIfile\fP [\fIfile\fP ...]

.SH DESCRIPTION
Add an OCI artifact to the local store from the local filesystem.  You must
provide at least one file to create the artifact, but several can also be
added.

.PP
Artifacts automatically include a creation timestamp in the
\fBorg.opencontainers.image.created\fR annotation using RFC3339Nano format. When using
the \fB--append\fR option, the original creation timestamp is preserved.

.SH OPTIONS
.SS \fB--annotation\fP=\fIannotation=value\fP
Set an annotation on the entry for the specified image or artifact.

.PP
Note: Set annotations for each file being added. The annotation "org.opencontainers.image.title" is used
to name the layer when mounted into a container, this title must be unigue for each artifact layer.

.SS \fB--append\fP, \fB-a\fP
Append files to an existing artifact. This option cannot be used with the \fB--type\fP option.

.SS \fB--file-type\fP
Set the media type of the artifact file instead of allowing detection to determine the type

.SS \fB--help\fP
Print usage statement.

.SS \fB--replace\fP
If an artifact with the same name already exists, replace and remove it. The default is \fBfalse\fP\&.
This option cannot be used with the \fB--append\fP option.

.SS \fB--type\fP
Set a type for the artifact being added.

.SH EXAMPLES
Add a single file to an artifact

.EX
$ podman artifact add quay.io/myartifact/myml:latest /tmp/foobar.ml
0fe1488ecdef8cc4093e11a55bc048d9fc3e13a4ba846efd24b5a715006c95b3
.EE

.PP
Add OCI artifact to the store with type:

.EX
$ podman artifact add --artifact-type application/com.example.ai --file-type application/vnd.gguf quay.io/myimage/myartifact:latest /home/user/model.gguf
.EE

.PP
Replace an existing artifact with the same name

.EX
$ podman artifact add quay.io/myartifact/myml:latest /tmp/foobar.ml
0fe1488ecdef8cc4093e11a55bc048d9fc3e13a4ba846efd24b5a715006c95b3
.EE

.PP
Add multiple files to an artifact

.EX
$ podman artifact add quay.io/myartifact/myml:latest /tmp/foobar1.ml /tmp/foobar2.ml
1487acae11b5a30948c50762882036b41ac91a7b9514be8012d98015c95ddb78
.EE

.PP
Add files to an existing OCI artifact

.EX
$ podman artifact add --append quay.io/myimage/myartifact:latest /home/user/config.yaml
.EE

.PP
Create artifact with the layer title name being replaced, and then mount into a container.

.EX
podman artifact add --annotation org.opencontainers.image.title=smollm2 quay.io/myreg/smollm2:latest blobs/sha256-4d2396b16114669389d7555c15a1592aad584750310f648edad5ca8c4eccda17
podman run --mount type=artifact,source=quay.io/myreg/smollm2:latest,destination=/mnt fedora ls -l /mnt
smollm2
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-artifact(1)\fP

.SH HISTORY
Jan 2025, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
