'\" t
.nh
.TH podman-farm 1
.SH NAME
podman-farm \- Farm out builds to machines running podman for different architectures

.SH SYNOPSIS
\fBpodman farm\fP \fIsubcommand\fP

.SH DESCRIPTION
Farm out builds to machines running Podman for different architectures.

.PP
Manage farms by creating, updating, and removing them.

.PP
Note: All farm machines must have a minimum podman version of v4.9.0.

.PP
Podman manages the farms by writing and reading the \fBpodman-connections.json\fR file located under
\fB$XDG_CONFIG_HOME/containers\fR or if the env is not set it defaults to \fB$HOME/.config/containers\fR\&.
Or the \fBPODMAN_CONNECTIONS_CONF\fR environment variable can be set to a full file path which podman
will use instead.
This file is managed by the podman commands and should never be edited by users directly. To manually
configure the farms use the \fB[farm]\fR section in containers.conf.

.PP
If the ReadWrite column in the \fBpodman farm list\fP output is set to true the farm is stored in the
\fBpodman-connections.json\fR file otherwise it is stored in containers.conf and can therefore not be
edited with the \fBpodman farm remove/update\fP commands. It can still be used with \fBpodman farm build\fP\&.

.SH COMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
build	podman-farm-build(1)	T{
Build images on farm nodes, then bundle them into a manifest list
T}
create	podman-farm-create(1)	Create a new farm
list	podman-farm-list(1)	List the existing farms
remove	podman-farm-remove(1)	Delete one or more farms
update	podman-farm-update(1)	Update an existing farm
.TE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
July 2023, Originally compiled by Urvashi Mohnani (umohnani at redhat dot com)
