'\" t
.nh
.TH podman-secret-inspect 1
.SH NAME
podman-secret-inspect \- Display detailed information on one or more secrets

.SH SYNOPSIS
\fBpodman secret inspect\fP [\fIoptions\fP] \fIsecret\fP [...]

.SH DESCRIPTION
Inspects the specified secret.

.PP
By default, this renders all results in a JSON array. If a format is specified, the given template is executed for each result.
Secrets can be queried individually by providing their full name or a unique partial name.

.SH OPTIONS
.SS \fB--format\fP, \fB-f\fP=\fIformat\fP
Format secret output using Go template.

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.CreatedAt ...	T{
When secret was created (relative timestamp, human-readable)
T}
\&.ID	ID of secret
\&.SecretData	T{
Secret Data (Displayed only with --showsecret option)		
T}
\&.Spec ...	Details of secret
\&.Spec.Driver ...	Driver info
\&.Spec.Driver.Name	Driver name (string)
\&.Spec.Driver.Options ...	T{
Driver options (map of driver-specific options)
T}
\&.Spec.Labels ...	Labels for this secret
\&.Spec.Name	Name of secret
\&.UpdatedAt ...	T{
When secret was last updated (relative timestamp, human-readable)
T}
.TE

.SS \fB--help\fP
Print usage statement.

.SS \fB--pretty\fP
Print inspect output in human-readable format. Ignores fields from \fB--format\fP\&.

.SS \fB--showsecret\fP
Display secret data

.SH EXAMPLES
Inspect the secret mysecret.

.EX
$ podman secret inspect mysecret
.EE

.PP
Inspect the secret mysecret and print it in a human readable format instead of JSON, with the default fields.

.EX
$ podman secret inspect --pretty mysecret
.EE

.PP
Inspect the secret mysecret and display the Name and Labels field.

.EX
$ podman secret inspect --format "{{.Spec.Name}} {{.Spec.Labels}}" mysecret
.EE

.PP
Inspect the secret mysecret and display the Name and SecretData fields. Note this will display the secret data to the screen.

.EX
$ podman secret inspect --showsecret --format "{{.Spec.Name}} {{.SecretData}}" mysecret
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-secret(1)\fP

.SH HISTORY
January 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
