'\" t
.nh
.TH podman-system-prune 1
.SH NAME
podman-system-prune \- Remove all unused pods, containers, images, networks, and volume data

.SH SYNOPSIS
\fBpodman system prune\fP [\fIoptions\fP]

.SH DESCRIPTION
\fBpodman system prune\fP removes all unused containers (both dangling and unreferenced), build containers, pods, networks, and optionally, volumes from local storage.

.PP
Use the \fB--all\fP option to delete all unused images.  Unused images are dangling images as well as any image that does not have any containers based on it.

.PP
By default, volumes are not removed to prevent important data from being deleted if there is currently no container using the volume. Use the \fB--volumes\fP flag when running the command to prune volumes as well.

.PP
By default, build containers are not removed to prevent interference with builds in progress. Use the \fB--build\fP flag when running the command to remove build containers as well.

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Recursively remove all unused pods, containers, images, networks, and volume data. (Maximum 50 iterations.)

.SS \fB--build\fP
Removes any build containers that were created during the build, but were not removed because the build was unexpectedly terminated.

.PP
Note: \fBThis is not safe operation and should be executed only when no builds are in progress. It can interfere with builds in progress.\fP

.SS \fB--external\fP
Tries to clean up remainders of previous containers or layers that are not references in the storage json files. These can happen in the case of unclean shutdowns or regular restarts in transient storage mode.

.PP
However, when using transient storage mode, the Podman database does not persist. This means containers leave the writable layers on disk after a reboot. When using a transient store, it is recommended that the \fBpodman system prune --external\fP command is run during boot.

.PP
This option is incompatible with \fB--all\fP and \fB--filter\fP and drops the default behaviour of removing unused resources.

.SS \fB--filter\fP=\fIfilters\fP
Provide filter values.

.PP
The \fIfilters\fP argument format is of \fBkey=value\fR\&. If there is more than one \fIfilter\fP, then pass multiple OPTIONS: \fB--filter\fP \fIfoo=bar\fP \fB--filter\fP \fIbif=baz\fP\&.

.PP
Supported filters:

.TS
allbox;
l l 
l l .
\fBFilter\fP	\fBDescription\fP
label	T{
Only remove containers and images, with (or without, in the case of label!=[...] is used) the specified labels.
T}
until	T{
Only remove containers and images created before given timestamp.
T}
.TE

.PP
The \fBlabel\fR \fIfilter\fP accepts two formats. One is the \fBlabel\fR=\fIkey\fP or \fBlabel\fR=\fIkey\fP=\fIvalue\fP, which removes containers and images with the specified labels. The other format is the \fBlabel!\fR=\fIkey\fP or \fBlabel!\fR=\fIkey\fP=\fIvalue\fP, which removes containers and images without the specified labels.

.PP
The \fBuntil\fR \fIfilter\fP can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. 10m, 1h30m) computed relative to the machine’s time.

.SS \fB--force\fP, \fB-f\fP
Do not prompt for confirmation

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--volumes\fP
Prune volumes currently unused by any container

.SH EXAMPLES
Prune all containers, pods, networks and dangling images.

.EX
$ podman system prune
WARNING! This command removes:
	- all stopped containers
	- all networks not used by at least one container
	- all dangling images
	- all dangling build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
.EE

.PP
Prune all containers, pods, and networks that are not in use.

.EX
$ podman system prune --all
WARNING! This command removes:
	- all stopped containers
	- all networks not used by at least one container
	- all images without at least one container associated with them
	- all build cache

Are you sure you want to continue? [y/N] y
Deleted Images
ce21f047f73644dcb9cd55ad247433fb47ade48ad4f4e676881fbcb2d5735c76
c874afc1f445044eaa821da0c32328707406e546a688d8c4c22587a5f88a1992
2fce09cfad57c6de112654eeb6f6da1851f3ced1cff7ac0002378642c2c7ca84
0cd6d2e072175191823999cd189f8d262ba5e460271095570d8cffb1d9072e9a
172bdaffe628cc7b7f8b7b6695438afc612a9833382f5968a06740a3804c3b64
bf07fec943ec23054f3b81c0e65926a1c83dc82c50933dc6372c60e09fdb2d4f
b2f735cbb571dd6a28e66455af0623ecc81f9c5b74259d3e04b3bac3b178e965
cea2ff433c610f5363017404ce989632e12b953114fefc6f597a58e813c15d61
Deleted Networks
podman-default-kube-network
Total reclaimed space: 3.372GB
.EE

.PP
Prune all containers, build containers, pods, networks and dangling images.

.EX
$ podman system prune --build
WARNING! This command removes:
	- all stopped containers
	- all networks not used by at least one container
	- all build containers
	- all dangling images
	- all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers
a8bfed41990114767c933d27bf5508b01cdc0f641dc36037b349648347c6ea64
Deleted Images
055733a33e7a78efa27d3c682df97a9e0489133bef071745144c8d0edda2d708
Total reclaimed space: 1.4GB
.EE

.PP
Prune containers by label.

.EX
$ podman system prune --filter label=role=cleanup
WARNING! This command removes:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers
5cd96fb787274db888f8b587c3690be1edea25b7f66b030037c528e2cea10b34
Total reclaimed space: 24.55kB
.EE

.PP
Prune containers filter until.
$ podman system prune --filter until=2m
WARNING! This command removes:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache

.PP
Are you sure you want to continue? [y/N] y
Deleted Containers
a12f9f6f2d901bc145c1e2c27dc8e5e2d04050854f4d9e01a6e10b1019e2d345
0d08f2e467cbff04b63ccd83efeb6ccc6161f54c27d5100d1194defe7ea73cf7
815dc403e1bc85bfa4a9d3184cbbe77fd019ea66780bf0b42e8726d5956d9bd3
Total reclaimed space: 74.14kB

.EX

With `--force` flag
.EE

.PP
$ podman system prune --force
Total reclaimed space: 0B
```

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-system(1)\fP

.SH HISTORY
February 2019, Originally compiled by Dan Walsh (dwalsh at redhat dot com)
December 2020, converted filter information from docs.docker.com documentation by Dan Walsh (dwalsh at redhat dot com)
