'\" t
.nh
.TH podman-machine-os 1
.SH NAME
podman-machine-os \- Manage a Podman virtual machine's OS

.SH SYNOPSIS
\fBpodman machine os\fP \fIsubcommand\fP

.SH DESCRIPTION
\fBpodman machine os\fR is a set of subcommands that manage a Podman virtual machine's operating system.

.SH SUBCOMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
apply	podman-machine-os-apply(1)	T{
Apply an OCI image to a Podman Machine's OS
T}
.TE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP, \fBpodman-machine-os-apply(1)\fP

.SH HISTORY
February 2023, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
