'\" t
.nh
.TH podman-kube 1
.SH NAME
podman-kube \- Play containers, pods or volumes based on a structured input file

.SH SYNOPSIS
\fBpodman kube\fP \fIsubcommand\fP

.SH DESCRIPTION
The kube command recreates containers, pods or volumes based on the input from a structured (like YAML)
file input.  Containers are automatically started.

.PP
Note: The kube commands in podman focus on simplifying the process of moving containers from podman to a Kubernetes
environment and from a Kubernetes environment back to podman. Podman is not replicating the kubectl CLI. Once containers
are deployed to a Kubernetes cluster from podman, please use \fBkubectl\fR to manage the workloads in the cluster.

.SH COMMANDS
.TS
allbox;
l l l 
l l l .
\fBCommand\fP	\fBMan Page\fP	\fBDescription\fP
apply	podman-kube-apply(1)	T{
Apply Kubernetes YAML based on containers, pods, or volumes to a Kubernetes cluster
T}
down	podman-kube-down(1)	T{
Remove containers and pods based on Kubernetes YAML.
T}
generate	podman-kube-generate(1)	T{
Generate Kubernetes YAML based on containers, pods or volumes.
T}
play	podman-kube-play(1)	T{
Create containers, pods and volumes based on Kubernetes YAML.
T}
.TE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBpodman-container(1)\fP, \fBpodman-kube-play(1)\fP, \fBpodman-kube-down(1)\fP, \fBpodman-kube-generate(1)\fP, \fBpodman-kube-apply(1)\fP

.SH HISTORY
December 2018, Originally compiled by Brent Baude (bbaude at redhat dot com)
