.nh
.TH podman-volume-import 1
.SH NAME
podman-volume-import \- Import tarball contents into an existing podman volume

.SH SYNOPSIS
\fBpodman volume import\fP \fIvolume\fP [\fIsource\fP]

.SH DESCRIPTION
\fBpodman volume import\fP imports the contents of a tarball into the podman volume's mount point.
The contents of the volume is merged with the content of the tarball with the latter taking precedence.
\fBpodman volume import\fP can consume piped input when using \fB-\fR as source path.

.PP
The given volume must already exist and is not created by podman volume import.

.SS \fB--help\fP
Print usage statement

.SH EXAMPLES
Import named volume content from the specified file.

.EX
$ podman volume import myvol test.tar
.EE

.PP
Import named volume content from stdin.

.EX
$ gunzip -c hello.tar.gz | podman volume import myvol -
.EE

.PP
Export the content from named volume and pipe it into the named volume via stdin.

.EX
$ podman volume export oldmyvol | podman volume import myvol -
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-volume(1)\fP, \fBpodman-volume-export(1)\fP
