.nh
.TH podman-network-rm 1
.SH NAME
podman-network-rm \- Remove one or more networks

.SH SYNOPSIS
\fBpodman network rm\fP [\fIoptions\fP] [\fInetwork...\fP]

.SH DESCRIPTION
Delete one or more Podman networks.

.SH OPTIONS
.SS \fB--force\fP, \fB-f\fP
The \fBforce\fR option removes all containers that use the named network. If the container is
running, the container is stopped and removed.

.SS \fB--time\fP, \fB-t\fP=\fIseconds\fP
Seconds to wait before forcibly stopping the running containers that are using the specified network. The --force option must be specified to use the --time option. Use -1 for infinite wait.

.SH EXAMPLES
Delete specified network:

.EX
# podman network rm podman9
podman9
.EE

.PP
Delete specified network and all containers associated with the network:

.EX
# podman network rm -f fred
fred
.EE

.PP
Delete specified network and all containers associated with the network after waiting up to 15 seconds:

.EX
# podman network rm --force --time 15 fred
fred
.EE

.SH Exit Status
\fB0\fP   All specified networks removed

.PP
\fB1\fP   One of the specified networks did not exist, and no other failures

.PP
\fB2\fP   The network is in use by a container or a Pod

.PP
\fB125\fP The command fails for any other reason

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP

.SH HISTORY
August 2019, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
