.nh
.TH podman-network-disconnect 1
.SH NAME
podman-network-disconnect \- Disconnect a container from a network

.SH SYNOPSIS
\fBpodman network disconnect\fP [\fIoptions\fP] network container

.SH DESCRIPTION
Disconnects a container from a network. A container can be disconnected from a network by name or by ID.
If all networks are disconnected from the container, it behaves like a container created with \fB--network=none\fR
and it does not have network connectivity until a network is connected again.

.SH OPTIONS
.SS \fB--force\fP, \fB-f\fP
Force the container to disconnect from a network

.SH EXAMPLE
Disconnect container from specified network:

.EX
podman network disconnect test web
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-network(1)\fP, \fBpodman-network-connect(1)\fP

.SH HISTORY
November 2020, Originally compiled by Brent Baude bbaude@redhat.com
\[la]mailto:bbaude@redhat.com\[ra]
