.nh
.TH podman-untag 1
.SH NAME
podman-untag \- Remove one or more names from a locally-stored image

.SH SYNOPSIS
\fBpodman untag\fP \fIimage\fP [\fIname\fP[:\fItag\fP]...]

.PP
\fBpodman image untag\fP \fIimage\fP [\fIname\fP[:\fItag\fP]...]

.SH DESCRIPTION
Remove one or more names from an image in the local storage.  The image can be referred to by ID or reference.  If no name is specified, all names are removed from the image.  If a specified name is a short name and does not include a registry, \fBlocalhost/\fR is prefixed (e.g., \fBfedora\fR -> \fBlocalhost/fedora\fR). If a specified name does not include a tag, \fB:latest\fR is appended (e.g., \fBlocalhost/fedora\fR -> \fBlocalhost/fedora:latest\fR).

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLES
Remove all tags from the specified image.

.EX
$ podman untag 0e3bbc2
.EE

.PP
Remove tag from specified image.

.EX
$ podman untag imageName:latest otherImageName:latest
.EE

.PP
Remove multiple tags from the specified image.

.EX
$ podman untag httpd myhttpd myregistryhost:5000/fedora/httpd:v2
.EE

.SH SEE ALSO
\fBpodman(1)\fP

.SH HISTORY
December 2019, Originally compiled by Sascha Grunert sgrunert@suse.com
\[la]mailto:sgrunert@suse.com\[ra]
