.nh
.TH podman-pod-top 1
.SH NAME
podman-pod-top \- Display the running processes of containers in a pod

.SH SYNOPSIS
\fBpodman pod top\fP [\fIoptions\fP] \fIpod\fP [\fIformat-descriptors\fP]

.SH DESCRIPTION
Display the running processes of containers in a pod. The \fIformat-descriptors\fP are ps (1) compatible AIX format
descriptors but extended to print additional information, such as the seccomp mode or the effective capabilities
of a given process. The descriptors can either be passed as separate arguments or as a single comma-separated argument.

.SH OPTIONS
.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SS \fB--latest\fP, \fB-l\fP
Instead of providing the pod name or ID, use the last created pod.
Note: the last started pod can be from other users of Podman on the host machine.
(This option is not available with the remote Podman client, including Mac and Windows
(excluding WSL2) machines)

.SH FORMAT DESCRIPTORS
For a full list of available descriptors, see podman-top(1)

.SH EXAMPLES
Print top data for the specified pod.
By default, \fBpodman-pod-top\fR prints data similar to \fBps -ef\fR:

.EX
$ podman pod top b031293491cc
USER   PID   PPID   %CPU    ELAPSED             TTY   TIME   COMMAND
root   1     0      0.000   2h5m38.737137571s   ?     0s     top
root   8     0      0.000   2h5m15.737228361s   ?     0s     top
.EE

.PP
The output can be controlled by specifying format descriptors as arguments after the pod.

.PP
Print the pod top data fields pid,seccomp, args and %C on the latest pod created. (This -l option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)

.EX
$ podman pod top -l pid seccomp args %C
PID   SECCOMP   COMMAND   %CPU
1     filter    top       0.000
1     filter    /bin/sh   0.000
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-pod(1)\fP, \fBps(1)\fP, \fBseccomp(2)\fP, \fBproc(5)\fP, \fBcapabilities(7)\fP

.SH HISTORY
August 2018, Originally compiled by Peter Hunt pehunt@redhat.com
\[la]mailto:pehunt@redhat.com\[ra]
