'\" t
.nh
.TH podman-machine-list 1
.SH NAME
podman-machine-list \- List virtual machines

.SH SYNOPSIS
\fBpodman machine list\fP [\fIoptions\fP]

.PP
\fBpodman machine ls\fP [\fIoptions\fP]

.SH DESCRIPTION
List Podman managed virtual machines.

.PP
Podman on MacOS and Windows requires a virtual machine. This is because containers are Linux -
containers do not run on any other OS because containers' core functionality are
tied to the Linux kernel. Podman machine must be used to manage MacOS and Windows machines,
but can be optionally used on Linux.

.PP
Rootless only.

.PP
NOTE: The podman-machine configuration file is managed under the
\fB$XDG_CONFIG_HOME/containers/podman/machine/\fR directory. Changing the \fB$XDG_CONFIG_HOME\fR
environment variable while the machines are running can lead to unexpected behavior.
(see podman(1))

.SH OPTIONS
.SS \fB--all-providers\fP
Show machines from all providers

.SS \fB--format\fP=\fIformat\fP
Change the default output format.  This can be of a supported type like 'json'
or a Go template.
Valid placeholders for the Go template are listed below:

.TS
allbox;
l l 
l l .
\fB\fBPlaceholder\fP\fP	\fB\fBDescription\fP\fP
\&.CPUs	Number of CPUs
\&.Created	Time since VM creation
\&.Default	Is default machine
\&.DiskSize	Disk size of machine
\&.IdentityPath	Path to ssh identity file
\&.LastUp	Time since the VM was last run
\&.Memory	Allocated memory for machine
\&.Name	VM name
\&.Port	T{
SSH Port to use to connect to VM
T}
\&.RemoteUsername	T{
VM Username for rootless Podman
T}
\&.Running	Is machine running
\&.Stream	Stream name
\&.Swap	Allocated swap for machine
\&.UserModeNetworking	T{
Whether machine uses user-mode networking
T}
\&.VMType	VM type
.TE

.SS \fB--help\fP
Print usage statement.

.SS \fB--noheading\fP, \fB-n\fP
Omit the table headings from the listing.

.SS \fB--quiet\fP, \fB-q\fP
Only print the name of the machine. This also implies no table heading
is printed.

.SH EXAMPLES
List all Podman machines.

.EX
$ podman machine list
NAME                    VM TYPE     CREATED      LAST UP      CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        2 weeks ago  2 weeks ago  1           2.147GB     10.74GB
.EE

.PP
List all Podman machines using the specified table format.

.EX
$ podman machine ls --format "table {{.Name}}\\t{{.VMType}}\\t{{.Created}}\\t{{.LastUp}}"
NAME                    VM TYPE     CREATED      LAST UP
podman-machine-default  qemu        2 weeks ago  2 weeks ago
.EE

.PP
List all Podman machines in json format.

.EX
$ podman machine ls --format json
[
    {
        "Name": "podman-machine-default",
        "Default": false,
        "Created": "2021-12-27T10:36:14.373347492-05:00",
        "Running": false,
        "LastUp": "2021-12-27T11:22:50.17333371-05:00",
        "Stream": "default",
        "VMType": "qemu",
        "CPUs": 1,
        "Memory": "2147483648",
        "DiskSize": "10737418240"
    }
]
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
March 2021, Originally compiled by Ashley Cui acui@redhat.com
\[la]mailto:acui@redhat.com\[ra]
