.nh
.TH podman-manifest-rm 1
.SH NAME
podman-manifest-rm \- Remove manifest list or image index from local storage

.SH SYNOPSIS
\fBpodman manifest rm\fP [\fIoptions\fP] \fIlist-or-index\fP [...]

.SH DESCRIPTION
Removes one or more locally stored manifest lists.

.SH OPTIONS
.SS \fB--ignore\fP, \fB-i\fP
If a specified manifest does not exist in the local storage, ignore it and do not throw an error.

.SH EXAMPLES
.EX
podman manifest rm listid
.EE

.EX
podman manifest rm --ignore listid1 listid2
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-manifest(1)\fP,  \fBcontainers-storage.conf(5)\fP
