.nh
.TH podman-machine-cp 1
.SH NAME
podman-machine-cp \- Securely copy contents between the host and the virtual machine

.SH SYNOPSIS
\fBpodman machine cp\fP [\fIoptions\fP] \fIsrc_path\fP \fIdest_path\fP

.SH DESCRIPTION
Use secure copy (scp) to copy files or directories between the virtual machine
and your host machine.

.PP
\fBpodman machine cp\fR does not support copying between two virtual machines,
which would require two machines running simultaneously.

.PP
Additionally, \fBpodman machine cp\fR will automatically do a recursive copy of
files and directories.

.SH OPTIONS
.SS \fB--help\fP
Print usage statement.

.SS \fB--quiet\fP, \fB-q\fP
Suppress copy status output.

.SH EXAMPLES
Copy a file from your host to the running Podman Machine.

.EX
$ podman machine cp ~/configuration.txt podman-machine-default:~/configuration.txt
\&...
Copy Successful
.EE

.PP
Copy a file from the running Podman Machine to your host.

.EX
$ podman machine cp podman-machine-default:~/logs/log.txt ~/logs/podman-machine-default.txt
\&...
Copy Successful
.EE

.PP
Copy a directory from your host to the running Podman Machine.

.EX
$ podman machine cp ~/.config podman-machine-default:~/.config
\&...
Copy Successful
.EE

.PP
Copy a directory from the running Podman Machine to your host.

.EX
$ podman machine cp podman-machine-default:~/.config ~/podman-machine-default.config
\&...
Copy Successful
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-machine(1)\fP

.SH HISTORY
February 2025, Originally compiled by Jake Correnti jcorrent@redhat.com
\[la]mailto:jcorrent@redhat.com\[ra]
