.nh
.TH podman-logout 1
.SH NAME
podman-logout \- Log out of a container registry

.SH SYNOPSIS
\fBpodman logout\fP [\fIoptions\fP] \fIregistry\fP

.SH DESCRIPTION
\fBpodman logout\fP logs out of a specified registry server by deleting the cached credentials
stored in the \fBauth.json\fP file. If the registry is not specified, the first registry under [registries.search]
from registries.conf is used. The path of the authentication file can be overridden by the user by setting the \fBauthfile\fP flag.
The default path used is \fB${XDG_RUNTIME_DIR}/containers/auth.json\fP\&. For more details about format and configurations of the auth,json file, see containers-auth.json(5)
All the cached credentials can be removed by setting the \fBall\fP flag.

.PP
\fBpodman [GLOBAL OPTIONS]\fP

.PP
\fBpodman logout [GLOBAL OPTIONS]\fP

.PP
\fBpodman logout [OPTIONS] REGISTRY [GLOBAL OPTIONS]\fP

.SH OPTIONS
.SS \fB--all\fP, \fB-a\fP
Remove the cached credentials for all registries in the auth file

.SS \fB--authfile\fP=\fIpath\fP
Path of the authentication file. Default is \fB${XDG_RUNTIME_DIR}/containers/auth.json\fR on Linux, and \fB$HOME/.config/containers/auth.json\fR on Windows/macOS.
The file is created by \fBpodman login\fP\&. If the authorization state is not found there, \fB$HOME/.docker/config.json\fR is checked, which is set using \fBdocker login\fP\&.

.PP
Note: There is also the option to override the default path of the authentication file by setting the \fBREGISTRY_AUTH_FILE\fR environment variable. This can be done with \fBexport REGISTRY_AUTH_FILE=\fIpath\fP\fP\&.

.SS \fB--compat-auth-file\fP=\fIpath\fP
Instead of updating the default credentials file, update the one at \fIpath\fP, and use a Docker-compatible format.

.SS \fB--help\fP, \fB-h\fP
Print usage statement

.SH EXAMPLES
Remove login credentials for the docker.io registry from the authentication file:

.EX
$ podman logout docker.io
.EE

.PP
Remove login credentials for the docker.io registry from the authdir/myauths.json file:

.EX
$ podman logout --authfile authdir/myauths.json docker.io
.EE

.PP
Remove login credentials for all registries:

.EX
$ podman logout --all
.EE

.SH SEE ALSO
\fBpodman(1)\fP, \fBpodman-login(1)\fP, \fBcontainers-auth.json(5)\fP

.SH HISTORY
August 2017, Originally compiled by Urvashi Mohnani umohnani@redhat.com
\[la]mailto:umohnani@redhat.com\[ra]
